<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['title' => 'موسیان','province_id'=>'1']);
        City::create(['title' => 'اسکو','province_id'=>'1']);
        City::create(['title' => 'اهر','province_id'=>'1']);
        City::create(['title' => 'ایلخچی','province_id'=>'1']);
        City::create(['title' => 'آبش احمد','province_id'=>'1']);
        City::create(['title' => 'آذرشهر','province_id'=>'1']);
        City::create(['title' => 'آقکند','province_id'=>'1']);
        City::create(['title' => 'باسمنج','province_id'=>'1']);
        City::create(['title' => 'بخشایش','province_id'=>'1']);
        City::create(['title' => 'بستان آباد','province_id'=>'1']);
        City::create(['title' => 'بناب','province_id'=>'1']);
        City::create(['title' => 'بناب جدید','province_id'=>'1']);
        City::create(['title' => 'تبریز','province_id'=>'1']);
        City::create(['title' => 'ترک','province_id'=>'1']);
        City::create(['title' => 'ترکمانچای','province_id'=>'1']);
        City::create(['title' => 'تسوج','province_id'=>'1']);
        City::create(['title' => 'تیکمه داش','province_id'=>'1']);
        City::create(['title' => 'جلفا','province_id'=>'1']);
        City::create(['title' => 'خاروانا','province_id'=>'1']);
        City::create(['title' => 'خامنه','province_id'=>'1']);
        City::create(['title' => 'خراجو','province_id'=>'1']);
        City::create(['title' => 'خسروشهر','province_id'=>'1']);
        City::create(['title' => 'خمارلو','province_id'=>'1']);
        City::create(['title' => 'خواجه','province_id'=>'1']);
        City::create(['title' => 'دوزدوزان','province_id'=>'1']);
        City::create(['title' => 'زرنق','province_id'=>'1']);
        City::create(['title' => 'زنوز','province_id'=>'1']);
        City::create(['title' => 'سراب','province_id'=>'1']);
        City::create(['title' => 'سردرود','province_id'=>'1']);
        City::create(['title' => 'سیس','province_id'=>'1']);
        City::create(['title' => 'شبستر','province_id'=>'1']);
        City::create(['title' => 'شربیان','province_id'=>'1']);
        City::create(['title' => 'شرفخانه','province_id'=>'1']);
        City::create(['title' => 'شندآباد','province_id'=>'1']);
        City::create(['title' => 'شهرجدیدسهند','province_id'=>'1']);
        City::create(['title' => 'صوفیان','province_id'=>'1']);
        City::create(['title' => 'عجب شیر','province_id'=>'1']);
        City::create(['title' => 'قره آغاج','province_id'=>'1']);
        City::create(['title' => 'کشکسرای','province_id'=>'1']);
        City::create(['title' => 'کلوانق','province_id'=>'1']);
        City::create(['title' => 'کلیبر','province_id'=>'1']);
        City::create(['title' => 'کوزه کنان','province_id'=>'1']);
        City::create(['title' => 'گوگان','province_id'=>'1']);
        City::create(['title' => 'لیلان','province_id'=>'1']);
        City::create(['title' => 'مراغه','province_id'=>'1']);
        City::create(['title' => 'مرند','province_id'=>'1']);
        City::create(['title' => 'ملکان','province_id'=>'1']);
        City::create(['title' => 'ممقان','province_id'=>'1']);
        City::create(['title' => 'مهربان','province_id'=>'1']);
        City::create(['title' => 'میانه','province_id'=>'1']);
        City::create(['title' => 'نظرکهریزی','province_id'=>'1']);
        City::create(['title' => 'وایقان','province_id'=>'1']);
        City::create(['title' => 'ورزقان','province_id'=>'1']);
        City::create(['title' => 'هادیشهر','province_id'=>'1']);
        City::create(['title' => 'هریس','province_id'=>'1']);
        City::create(['title' => 'هشترود','province_id'=>'1']);
        City::create(['title' => 'هوراند','province_id'=>'1']);
        City::create(['title' => 'یامچی','province_id'=>'1']);
        City::create(['title' => 'ارومیه','province_id'=>'2']);
        City::create(['title' => 'اشنویه','province_id'=>'2']);
        City::create(['title' => 'ایواوغلی','province_id'=>'2']);
        City::create(['title' => 'آواجیق','province_id'=>'2']);
        City::create(['title' => 'باروق','province_id'=>'2']);
        City::create(['title' => 'بازرگان','province_id'=>'2']);
        City::create(['title' => 'بوکان','province_id'=>'2']);
        City::create(['title' => 'پلدشت','province_id'=>'2']);
        City::create(['title' => 'پیرانشهر','province_id'=>'2']);
        City::create(['title' => 'تازه شهر','province_id'=>'2']);
        City::create(['title' => 'تکاب','province_id'=>'2']);
        City::create(['title' => 'چهاربرج','province_id'=>'2']);
        City::create(['title' => 'خلیفان','province_id'=>'2']);
        City::create(['title' => 'خوی','province_id'=>'2']);
        City::create(['title' => 'دیزج دیز','province_id'=>'2']);
        City::create(['title' => 'ربط','province_id'=>'2']);
        City::create(['title' => 'سردشت','province_id'=>'2']);
        City::create(['title' => 'سرو','province_id'=>'2']);
        City::create(['title' => 'سلماس','province_id'=>'2']);
        City::create(['title' => 'سیلوانه','province_id'=>'2']);
        City::create(['title' => 'سیمینه','province_id'=>'2']);
        City::create(['title' => 'سیه چشمه','province_id'=>'2']);
        City::create(['title' => 'شاهین دژ','province_id'=>'2']);
        City::create(['title' => 'شوط','province_id'=>'2']);
        City::create(['title' => 'فیرورق','province_id'=>'2']);
        City::create(['title' => 'قره ضیاءالدین','province_id'=>'2']);
        City::create(['title' => 'قطور','province_id'=>'2']);
        City::create(['title' => 'قوشچی','province_id'=>'2']);
        City::create(['title' => 'کشاورز','province_id'=>'2']);
        City::create(['title' => 'گردکشانه','province_id'=>'2']);
        City::create(['title' => 'ماکو','province_id'=>'2']);
        City::create(['title' => 'محمدیار','province_id'=>'2']);
        City::create(['title' => 'محمودآباد','province_id'=>'2']);
        City::create(['title' => 'مهاباد','province_id'=>'2']);
        City::create(['title' => 'میاندوآب','province_id'=>'2']);
        City::create(['title' => 'میرآباد','province_id'=>'2']);
        City::create(['title' => 'نالوس','province_id'=>'2']);
        City::create(['title' => 'نقده','province_id'=>'2']);
        City::create(['title' => 'نوشین','province_id'=>'2']);
        City::create(['title' => 'اردبیل','province_id'=>'3']);
        City::create(['title' => 'اصلاندوز','province_id'=>'3']);
        City::create(['title' => 'آبی بیگلو','province_id'=>'3']);
        City::create(['title' => 'بیله سوار','province_id'=>'3']);
        City::create(['title' => 'پارس آباد','province_id'=>'3']);
        City::create(['title' => 'تازه کند','province_id'=>'3']);
        City::create(['title' => 'تازه کندانگوت','province_id'=>'3']);
        City::create(['title' => 'جعفرآباد','province_id'=>'3']);
        City::create(['title' => 'خلخال','province_id'=>'3']);
        City::create(['title' => 'رضی','province_id'=>'3']);
        City::create(['title' => 'سرعین','province_id'=>'3']);
        City::create(['title' => 'عنبران','province_id'=>'3']);
        City::create(['title' => 'فخرآباد','province_id'=>'3']);
        City::create(['title' => 'کلور','province_id'=>'3']);
        City::create(['title' => 'گیوی','province_id'=>'3']);
        City::create(['title' => 'لاهرود','province_id'=>'3']);
        City::create(['title' => 'مرادلو','province_id'=>'3']);
        City::create(['title' => 'مشگین شهر','province_id'=>'3']);
        City::create(['title' => 'نمین','province_id'=>'3']);
        City::create(['title' => 'نیر','province_id'=>'3']);
        City::create(['title' => 'هشتجین','province_id'=>'3']);
        City::create(['title' => 'هیر','province_id'=>'3']);
        City::create(['title' => 'ابریشم','province_id'=>'4']);
        City::create(['title' => 'ابوزیدآباد','province_id'=>'4']);
        City::create(['title' => 'اردستان','province_id'=>'4']);
        City::create(['title' => 'اصفهان','province_id'=>'4']);
        City::create(['title' => 'افوس','province_id'=>'4']);
        City::create(['title' => 'انارک','province_id'=>'4']);
        City::create(['title' => 'ایمانشهر','province_id'=>'4']);
        City::create(['title' => 'آران وبیدگل','province_id'=>'4']);
        City::create(['title' => 'بادرود','province_id'=>'4']);
        City::create(['title' => 'باغ بهادران','province_id'=>'4']);
        City::create(['title' => 'بافران','province_id'=>'4']);
        City::create(['title' => 'برزک','province_id'=>'4']);
        City::create(['title' => 'برف انبار','province_id'=>'4']);
        City::create(['title' => 'بوئین ومیاندشت','province_id'=>'4']);
        City::create(['title' => 'بهاران شهر','province_id'=>'4']);
        City::create(['title' => 'بهارستان','province_id'=>'4']);
        City::create(['title' => 'پیربکران','province_id'=>'4']);
        City::create(['title' => 'تودشک','province_id'=>'4']);
        City::create(['title' => 'تیران','province_id'=>'4']);
        City::create(['title' => 'جندق','province_id'=>'4']);
        City::create(['title' => 'جوزدان','province_id'=>'4']);
        City::create(['title' => 'جوشقان وکامو','province_id'=>'4']);
        City::create(['title' => 'چادگان','province_id'=>'4']);
        City::create(['title' => 'چرمهین','province_id'=>'4']);
        City::create(['title' => 'چمگردان','province_id'=>'4']);
        City::create(['title' => 'حبیب آباد','province_id'=>'4']);
        City::create(['title' => 'حسن آباد','province_id'=>'4']);
        City::create(['title' => 'چمگردان','province_id'=>'4']);
        City::create(['title' => 'حنا','province_id'=>'4']);
        City::create(['title' => 'خالدآباد','province_id'=>'4']);
        City::create(['title' => 'خمینی شهر','province_id'=>'4']);
        City::create(['title' => 'خوانسار','province_id'=>'4']);
        City::create(['title' => 'خور','province_id'=>'4']);
        City::create(['title' => 'خوراسگان','province_id'=>'4']);
        City::create(['title' => 'خورزوق','province_id'=>'4']);
        City::create(['title' => 'داران','province_id'=>'4']);
        City::create(['title' => 'دامنه','province_id'=>'4']);
        City::create(['title' => 'درچه پیاز','province_id'=>'4']);
        City::create(['title' => 'دستگرد','province_id'=>'4']);
        City::create(['title' => 'دولت آباد','province_id'=>'4']);
        City::create(['title' => 'دهاقان','province_id'=>'4']);
        City::create(['title' => 'دهق','province_id'=>'4']);
        City::create(['title' => 'دیزیچه','province_id'=>'4']);
        City::create(['title' => 'رزوه','province_id'=>'4']);
        City::create(['title' => 'رضوانشهر','province_id'=>'4']);
        City::create(['title' => 'زاینده رود','province_id'=>'4']);
        City::create(['title' => 'زرین شهر','province_id'=>'4']);
        City::create(['title' => 'زواره','province_id'=>'4']);
        City::create(['title' => 'زیباشهر','province_id'=>'4']);
        City::create(['title' => 'سده لنجان','province_id'=>'4']);
        City::create(['title' => 'سفیدشهر','province_id'=>'4']);
        City::create(['title' => 'سگزی','province_id'=>'4']);
        City::create(['title' => 'سمیرم','province_id'=>'4']);
        City::create(['title' => 'شاپورآباد','province_id'=>'4']);
        City::create(['title' => 'شاهین شهر','province_id'=>'4']);
        City::create(['title' => 'شهرضا','province_id'=>'4']);
        City::create(['title' => 'طالخونچه','province_id'=>'4']);
        City::create(['title' => 'عسگران','province_id'=>'4']);
        City::create(['title' => 'علویچه','province_id'=>'4']);
        City::create(['title' => 'فرخی','province_id'=>'4']);
        City::create(['title' => 'فریدونشهر','province_id'=>'4']);
        City::create(['title' => 'فلاورجان','province_id'=>'4']);
        City::create(['title' => 'فولادشهر','province_id'=>'4']);
        City::create(['title' => 'قمصر','province_id'=>'4']);
        City::create(['title' => 'قهجاورستان','province_id'=>'4']);
        City::create(['title' => 'قهدریجان','province_id'=>'4']);
        City::create(['title' => 'کاشان','province_id'=>'4']);
        City::create(['title' => 'کرکوند','province_id'=>'4']);
        City::create(['title' => 'کلیشادوسودرجان','province_id'=>'4']);
        City::create(['title' => 'کمشچه','province_id'=>'4']);
        City::create(['title' => 'کمه','province_id'=>'4']);
        City::create(['title' => 'کوشک','province_id'=>'4']);
        City::create(['title' => 'کوهپایه','province_id'=>'4']);
        City::create(['title' => 'کهریزسنگ','province_id'=>'4']);
        City::create(['title' => 'گرگاب','province_id'=>'4']);
        City::create(['title' => 'گزبرخوار','province_id'=>'4']);
        City::create(['title' => 'گلپایگان','province_id'=>'4']);
        City::create(['title' => 'گلدشت','province_id'=>'4']);
        City::create(['title' => 'گلشن','province_id'=>'4']);
        City::create(['title' => 'گلشهر','province_id'=>'4']);
        City::create(['title' => 'گوگد','province_id'=>'4']);
        City::create(['title' => 'لای بید','province_id'=>'4']);
        City::create(['title' => 'مبارکه','province_id'=>'4']);
        City::create(['title' => 'محمدآباد','province_id'=>'4']);
        City::create(['title' => 'مشکات','province_id'=>'4']);
        City::create(['title' => 'منظریه','province_id'=>'4']);
        City::create(['title' => 'مهاباد','province_id'=>'4']);
        City::create(['title' => 'میمه','province_id'=>'4']);
        City::create(['title' => 'نائین','province_id'=>'4']);
        City::create(['title' => 'نجف آباد','province_id'=>'4']);
        City::create(['title' => 'نوش آباد','province_id'=>'4']);
        City::create(['title' => 'نیاسر','province_id'=>'4']);
        City::create(['title' => 'نیک آباد','province_id'=>'4']);
        City::create(['title' => 'ورزنه','province_id'=>'4']);
        City::create(['title' => 'ورنامخواست','province_id'=>'4']);
        City::create(['title' => 'وزوان','province_id'=>'4']);
        City::create(['title' => 'ونک','province_id'=>'4']);
        City::create(['title' => 'هرند','province_id'=>'4']);
        City::create(['title' => 'اشتهارد','province_id'=>'5']);
        City::create(['title' => 'آسارا','province_id'=>'5']);
        City::create(['title' => 'تنکمان','province_id'=>'5']);
        City::create(['title' => 'چهارباغ','province_id'=>'5']);
        City::create(['title' => 'سیف آباد','province_id'=>'5']);
        City::create(['title' => 'شهرجدیدهشتگرد','province_id'=>'5']);
        City::create(['title' => 'طالقان','province_id'=>'5']);
        City::create(['title' => 'کرج','province_id'=>'5']);
        City::create(['title' => 'کمال شهر','province_id'=>'5']);
        City::create(['title' => 'کوهسار','province_id'=>'5']);
        City::create(['title' => 'گرمدره','province_id'=>'5']);
        City::create(['title' => 'ماهدشت','province_id'=>'5']);
        City::create(['title' => 'محمدشهر','province_id'=>'5']);
        City::create(['title' => 'مشکین دشت','province_id'=>'5']);
        City::create(['title' => 'نظرآباد','province_id'=>'5']);
        City::create(['title' => 'هشتگرد','province_id'=>'5']);
        City::create(['title' => 'ارکواز','province_id'=>'6']);
        City::create(['title' => 'ایلام','province_id'=>'6']);
        City::create(['title' => 'ایوان','province_id'=>'6']);
        City::create(['title' => 'آبدانان','province_id'=>'6']);
        City::create(['title' => 'آسمان آباد','province_id'=>'6']);
        City::create(['title' => 'پهله','province_id'=>'6']);
        City::create(['title' => 'توحید','province_id'=>'6']);
        City::create(['title' => 'چوار','province_id'=>'6']);
        City::create(['title' => 'دره شهر','province_id'=>'6']);
        City::create(['title' => 'دلگشا','province_id'=>'6']);
        City::create(['title' => 'دهلران','province_id'=>'6']);
        City::create(['title' => 'زرنه','province_id'=>'6']);
        City::create(['title' => 'سراب باغ','province_id'=>'6']);
        City::create(['title' => 'سرابله','province_id'=>'6']);
        City::create(['title' => 'صالح آباد','province_id'=>'6']);
        City::create(['title' => 'لومار','province_id'=>'6']);
        City::create(['title' => 'مورموری','province_id'=>'6']);
        City::create(['title' => 'موسیان','province_id'=>'6']);
        City::create(['title' => 'مهران','province_id'=>'6']);
        City::create(['title' => 'میمه','province_id'=>'6']);
        City::create(['title' => 'امام حسن','province_id'=>'7']);
        City::create(['title' => 'انارستان','province_id'=>'7']);
        City::create(['title' => 'اهرم','province_id'=>'7']);
        City::create(['title' => 'آبپخش','province_id'=>'7']);
        City::create(['title' => 'آبدان','province_id'=>'7']);
        City::create(['title' => 'برازجان','province_id'=>'7']);
        City::create(['title' => 'بردخون','province_id'=>'7']);
        City::create(['title' => 'بردستان','province_id'=>'7']);
        City::create(['title' => 'بندردیر','province_id'=>'7']);
        City::create(['title' => 'بندردیلم','province_id'=>'7']);
        City::create(['title' => 'بندرریگ','province_id'=>'7']);
        City::create(['title' => 'بندرکنگان','province_id'=>'7']);
        City::create(['title' => 'بندرگناوه','province_id'=>'7']);
        City::create(['title' => 'بنک','province_id'=>'7']);
        City::create(['title' => 'بوشهر','province_id'=>'7']);
        City::create(['title' => 'تنگ ارم','province_id'=>'7']);
        City::create(['title' => 'جم','province_id'=>'7']);
        City::create(['title' => 'چغادک','province_id'=>'7']);
        City::create(['title' => 'خارک','province_id'=>'7']);
        City::create(['title' => 'خورموج','province_id'=>'7']);
        City::create(['title' => 'دالکی','province_id'=>'7']);
        City::create(['title' => 'دلوار','province_id'=>'7']);
        City::create(['title' => 'ریز','province_id'=>'7']);
        City::create(['title' => 'سعدآباد','province_id'=>'7']);
        City::create(['title' => 'سیراف','province_id'=>'7']);
        City::create(['title' => 'شبانکاره','province_id'=>'7']);
        City::create(['title' => 'شنبه','province_id'=>'7']);
        City::create(['title' => 'عسلویه','province_id'=>'7']);
        City::create(['title' => 'کاکی','province_id'=>'7']);
        City::create(['title' => 'کلمه','province_id'=>'7']);
        City::create(['title' => 'نخل تقی','province_id'=>'7']);
        City::create(['title' => 'وحدتیه','province_id'=>'7']);
        City::create(['title' => 'ارجمند','province_id'=>'8']);
        City::create(['title' => 'اسلامشهر','province_id'=>'8']);
        City::create(['title' => 'اندیشه','province_id'=>'8']);
        City::create(['title' => 'آبسرد','province_id'=>'8']);
        City::create(['title' => 'آبعلی','province_id'=>'8']);
        City::create(['title' => 'باغستان','province_id'=>'8']);
        City::create(['title' => 'باقرشهر','province_id'=>'8']);
        City::create(['title' => 'بومهن','province_id'=>'8']);
        City::create(['title' => 'پاکدشت','province_id'=>'8']);
        City::create(['title' => 'پردیس','province_id'=>'8']);
        City::create(['title' => 'پیشوا','province_id'=>'8']);
        City::create(['title' => 'تهران','province_id'=>'8']);
        City::create(['title' => 'جوادآباد','province_id'=>'8']);
        City::create(['title' => 'چهاردانگه','province_id'=>'8']);
        City::create(['title' => 'حسن آباد','province_id'=>'8']);
        City::create(['title' => 'دماوند','province_id'=>'8']);
        City::create(['title' => 'حسن آباد','province_id'=>'8']);
        City::create(['title' => 'رباط کریم','province_id'=>'8']);
        City::create(['title' => 'رودهن','province_id'=>'8']);
        City::create(['title' => 'ری','province_id'=>'8']);
        City::create(['title' => 'شاهدشهر','province_id'=>'8']);
        City::create(['title' => 'شریف آباد','province_id'=>'8']);
        City::create(['title' => 'شهریار','province_id'=>'8']);
        City::create(['title' => 'صالح آباد','province_id'=>'8']);
        City::create(['title' => 'صباشهر','province_id'=>'8']);
        City::create(['title' => 'صفادشت','province_id'=>'8']);
        City::create(['title' => 'صباشهر','province_id'=>'8']);
        City::create(['title' => 'فردوسیه','province_id'=>'8']);
        City::create(['title' => 'فرون آباد','province_id'=>'8']);
        City::create(['title' => 'فشم','province_id'=>'8']);
        City::create(['title' => 'فیروزکوه','province_id'=>'8']);
        City::create(['title' => 'قدس','province_id'=>'8']);
        City::create(['title' => 'قرچک','province_id'=>'8']);
        City::create(['title' => 'کهریزک','province_id'=>'8']);
        City::create(['title' => 'کیلان','province_id'=>'8']);
        City::create(['title' => 'گلستان','province_id'=>'8']);
        City::create(['title' => 'لواسان','province_id'=>'8']);
        City::create(['title' => 'ملارد','province_id'=>'8']);
        City::create(['title' => 'نسیم شهر','province_id'=>'8']);
        City::create(['title' => 'نصیرآباد','province_id'=>'8']);
        City::create(['title' => 'وحیدیه','province_id'=>'8']);
        City::create(['title' => 'ورامین','province_id'=>'8']);
        City::create(['title' => 'اردل','province_id'=>'9']);
        City::create(['title' => 'آلونی','province_id'=>'9']);
        City::create(['title' => 'باباحیدر','province_id'=>'9']);
        City::create(['title' => 'بروجن','province_id'=>'9']);
        City::create(['title' => 'بلداجی','province_id'=>'9']);
        City::create(['title' => 'بن','province_id'=>'9']);
        City::create(['title' => 'جونقان','province_id'=>'9']);
        City::create(['title' => 'چلگرد','province_id'=>'9']);
        City::create(['title' => 'سامان','province_id'=>'9']);
        City::create(['title' => 'سفیددشت','province_id'=>'9']);
        City::create(['title' => 'سودجان','province_id'=>'9']);
        City::create(['title' => 'سورشجان','province_id'=>'9']);
        City::create(['title' => 'شلمزار','province_id'=>'9']);
        City::create(['title' => 'شهرکرد','province_id'=>'9']);
        City::create(['title' => 'طاقانک','province_id'=>'9']);
        City::create(['title' => 'فارسان','province_id'=>'9']);
        City::create(['title' => 'فرادنبه','province_id'=>'9']);
        City::create(['title' => 'فرخ شهر','province_id'=>'9']);
        City::create(['title' => 'کیان','province_id'=>'9']);
        City::create(['title' => 'گندمان','province_id'=>'9']);
        City::create(['title' => 'گهرو','province_id'=>'9']);
        City::create(['title' => 'لردگان','province_id'=>'9']);
        City::create(['title' => 'مال خلیفه','province_id'=>'9']);
        City::create(['title' => 'ناغان','province_id'=>'9']);
        City::create(['title' => 'نافچ','province_id'=>'9']);
        City::create(['title' => 'نقنه','province_id'=>'9']);
        City::create(['title' => 'هفشجان','province_id'=>'9']);
        City::create(['title' => 'ارسک','province_id'=>'10']);
        City::create(['title' => 'اسدیه','province_id'=>'10']);
        City::create(['title' => 'اسفدن','province_id'=>'10']);
        City::create(['title' => 'اسلامیه','province_id'=>'10']);
        City::create(['title' => 'آرین شهر','province_id'=>'10']);
        City::create(['title' => 'آیسک','province_id'=>'10']);
        City::create(['title' => 'بشرویه','province_id'=>'10']);
        City::create(['title' => 'بیرجند','province_id'=>'10']);
        City::create(['title' => 'حاجی آباد','province_id'=>'10']);
        City::create(['title' => 'خضری دشت بیاض','province_id'=>'10']);
        City::create(['title' => 'خوسف','province_id'=>'10']);
        City::create(['title' => 'زهان','province_id'=>'10']);
        City::create(['title' => 'سرایان','province_id'=>'10']);
        City::create(['title' => 'سربیشه','province_id'=>'10']);
        City::create(['title' => 'سه قلعه','province_id'=>'10']);
        City::create(['title' => 'شوسف','province_id'=>'10']);
        City::create(['title' => 'طبس مسینا','province_id'=>'10']);
        City::create(['title' => 'فردوس','province_id'=>'10']);
        City::create(['title' => 'قائن','province_id'=>'10']);
        City::create(['title' => 'قهستان','province_id'=>'10']);
        City::create(['title' => 'گزیک','province_id'=>'10']);
        City::create(['title' => 'محمدشهر','province_id'=>'10']);
        City::create(['title' => 'مود','province_id'=>'10']);
        City::create(['title' => 'نهبندان','province_id'=>'10']);
        City::create(['title' => 'نیمبلوک','province_id'=>'10']);
        City::create(['title' => 'احمدآبادصولت','province_id'=>'11']);
        City::create(['title' => 'انابد','province_id'=>'11']);
        City::create(['title' => 'باجگیران','province_id'=>'11']);
        City::create(['title' => 'باخرز','province_id'=>'11']);
        City::create(['title' => 'بار','province_id'=>'11']);
        City::create(['title' => 'بایگ','province_id'=>'11']);
        City::create(['title' => 'بجستان','province_id'=>'11']);
        City::create(['title' => 'بردسکن','province_id'=>'11']);
        City::create(['title' => 'بیدخت','province_id'=>'11']);
        City::create(['title' => 'تایباد','province_id'=>'11']);
        City::create(['title' => 'تربت جام','province_id'=>'11']);
        City::create(['title' => 'تربت حیدریه','province_id'=>'11']);
        City::create(['title' => 'جغتای','province_id'=>'11']);
        City::create(['title' => 'جنگل','province_id'=>'11']);
        City::create(['title' => 'چاپشلو','province_id'=>'11']);
        City::create(['title' => 'چکنه','province_id'=>'11']);
        City::create(['title' => 'چناران','province_id'=>'11']);
        City::create(['title' => 'خرو','province_id'=>'11']);
        City::create(['title' => 'خلیل آباد','province_id'=>'11']);
        City::create(['title' => 'خواف','province_id'=>'11']);
        City::create(['title' => 'داورزن','province_id'=>'11']);
        City::create(['title' => 'درگز','province_id'=>'11']);
        City::create(['title' => 'درود','province_id'=>'11']);
        City::create(['title' => 'دولت آباد','province_id'=>'11']);
        City::create(['title' => 'رباط سنگ','province_id'=>'11']);
        City::create(['title' => 'رشتخوار','province_id'=>'11']);
        City::create(['title' => 'رضویه','province_id'=>'11']);
        City::create(['title' => 'روداب','province_id'=>'11']);
        City::create(['title' => 'ریوش','province_id'=>'11']);
        City::create(['title' => 'سبزوار','province_id'=>'11']);
        City::create(['title' => 'سرخس','province_id'=>'11']);
        City::create(['title' => 'سفیدسنگ','province_id'=>'11']);
        City::create(['title' => 'سلامی','province_id'=>'11']);
        City::create(['title' => 'سلطان آباد','province_id'=>'11']);
        City::create(['title' => 'سنگان','province_id'=>'11']);
        City::create(['title' => 'شادمهر','province_id'=>'11']);
        City::create(['title' => 'شاندیز','province_id'=>'11']);
        City::create(['title' => 'ششتمد','province_id'=>'11']);
        City::create(['title' => 'شهرآباد','province_id'=>'11']);
        City::create(['title' => 'شهرزو','province_id'=>'11']);
        City::create(['title' => 'صالح آباد','province_id'=>'11']);
        City::create(['title' => 'طرقبه','province_id'=>'11']);
        City::create(['title' => 'عشق آباد','province_id'=>'11']);
        City::create(['title' => 'فرهادگرد','province_id'=>'11']);
        City::create(['title' => 'فریمان','province_id'=>'11']);
        City::create(['title' => 'فیروزه','province_id'=>'11']);
        City::create(['title' => 'فیض آباد','province_id'=>'11']);
        City::create(['title' => 'قاسم آباد','province_id'=>'11']);
        City::create(['title' => 'قدمگاه','province_id'=>'11']);
        City::create(['title' => 'قلندرآباد','province_id'=>'11']);
        City::create(['title' => 'قوچان','province_id'=>'11']);
        City::create(['title' => 'کاخک','province_id'=>'11']);
        City::create(['title' => 'کاریز','province_id'=>'11']);
        City::create(['title' => 'کاشمر','province_id'=>'11']);
        City::create(['title' => 'کدکن','province_id'=>'11']);
        City::create(['title' => 'کلات','province_id'=>'11']);
        City::create(['title' => 'کندر','province_id'=>'11']);
        City::create(['title' => 'گلمکان','province_id'=>'11']);
        City::create(['title' => 'گناباد','province_id'=>'11']);
        City::create(['title' => 'لطف آباد','province_id'=>'11']);
        City::create(['title' => 'مزدآوند','province_id'=>'11']);
        City::create(['title' => 'مشهد','province_id'=>'11']);
        City::create(['title' => 'ملک آباد','province_id'=>'11']);
        City::create(['title' => 'نشتیفان','province_id'=>'11']);
        City::create(['title' => 'نصرآباد','province_id'=>'11']);
        City::create(['title' => 'نقاب','province_id'=>'11']);
        City::create(['title' => 'نوخندان','province_id'=>'11']);
        City::create(['title' => 'نیشابور','province_id'=>'11']);
        City::create(['title' => 'نیل شهر','province_id'=>'11']);
        City::create(['title' => 'همت آباد','province_id'=>'11']);
        City::create(['title' => 'یونسی','province_id'=>'11']);
        City::create(['title' => 'اسفراین','province_id'=>'12']);
        City::create(['title' => 'ایور','province_id'=>'12']);
        City::create(['title' => 'آشخانه','province_id'=>'12']);
        City::create(['title' => 'بجنورد','province_id'=>'12']);
        City::create(['title' => 'پیش قلعه','province_id'=>'12']);
        City::create(['title' => 'تیتکانلو','province_id'=>'12']);
        City::create(['title' => 'جاجرم','province_id'=>'12']);
        City::create(['title' => 'حصارگرمخان','province_id'=>'12']);
        City::create(['title' => 'درق','province_id'=>'12']);
        City::create(['title' => 'راز','province_id'=>'12']);
        City::create(['title' => 'سنخواست','province_id'=>'12']);
        City::create(['title' => 'شوقان','province_id'=>'12']);
        City::create(['title' => 'شیروان','province_id'=>'12']);
        City::create(['title' => 'صفی آباد','province_id'=>'12']);
        City::create(['title' => 'فاروج','province_id'=>'12']);
        City::create(['title' => 'قاضی','province_id'=>'12']);
        City::create(['title' => 'گرمه','province_id'=>'12']);
        City::create(['title' => 'لوجلی','province_id'=>'12']);
        City::create(['title' => 'اروندکنار','province_id'=>'13']);
        City::create(['title' => 'الوان','province_id'=>'13']);
        City::create(['title' => 'امیدیه','province_id'=>'13']);
        City::create(['title' => 'اندیمشک','province_id'=>'13']);
        City::create(['title' => 'اهواز','province_id'=>'13']);
        City::create(['title' => 'ایذه','province_id'=>'13']);
        City::create(['title' => 'آبادان','province_id'=>'13']);
        City::create(['title' => 'آغاجاری','province_id'=>'13']);
        City::create(['title' => 'باغ ملک','province_id'=>'13']);
        City::create(['title' => 'بستان','province_id'=>'13']);
        City::create(['title' => 'بندرامام خمینی','province_id'=>'13']);
        City::create(['title' => 'بندرماهشهر','province_id'=>'13']);
        City::create(['title' => 'بهبهان','province_id'=>'13']);
        City::create(['title' => 'ترکالکی','province_id'=>'13']);
        City::create(['title' => 'جایزان','province_id'=>'13']);
        City::create(['title' => 'جنت مکان','province_id'=>'13']);
        City::create(['title' => 'چغامیش','province_id'=>'13']);
        City::create(['title' => 'چمران','province_id'=>'13']);
        City::create(['title' => 'چوئبده','province_id'=>'13']);
        City::create(['title' => 'حسینیه','province_id'=>'13']);
        City::create(['title' => 'حمزه','province_id'=>'13']);
        City::create(['title' => 'حمیدیه','province_id'=>'13']);
        City::create(['title' => 'خرمشهر','province_id'=>'13']);
        City::create(['title' => 'دارخوین','province_id'=>'13']);
        City::create(['title' => 'دزآب','province_id'=>'13']);
        City::create(['title' => 'دزفول','province_id'=>'13']);
        City::create(['title' => 'دهدز','province_id'=>'13']);
        City::create(['title' => 'رامشیر','province_id'=>'13']);
        City::create(['title' => 'رامهرمز','province_id'=>'13']);
        City::create(['title' => 'رفیع','province_id'=>'13']);
        City::create(['title' => 'زهره','province_id'=>'13']);
        City::create(['title' => 'سالند','province_id'=>'13']);
        City::create(['title' => 'سردشت','province_id'=>'13']);
        City::create(['title' => 'سماله','province_id'=>'13']);
        City::create(['title' => 'سوسنگرد','province_id'=>'13']);
        City::create(['title' => 'شادگان','province_id'=>'13']);
        City::create(['title' => 'شاوور','province_id'=>'13']);
        City::create(['title' => 'شرافت','province_id'=>'13']);
        City::create(['title' => 'شوش','province_id'=>'13']);
        City::create(['title' => 'شوشتر','province_id'=>'13']);
        City::create(['title' => 'شیبان','province_id'=>'13']);
        City::create(['title' => 'صالح شهر','province_id'=>'13']);
        City::create(['title' => 'صالح مشطط','province_id'=>'13']);
        City::create(['title' => 'صفی آباد','province_id'=>'13']);
        City::create(['title' => 'صیدون','province_id'=>'13']);
        City::create(['title' => 'قلعه تل','province_id'=>'13']);
        City::create(['title' => 'قلعه خواجه','province_id'=>'13']);
        City::create(['title' => 'گتوند','province_id'=>'13']);
        City::create(['title' => 'گوریه','province_id'=>'13']);
        City::create(['title' => 'لالی','province_id'=>'13']);
        City::create(['title' => 'مسجدسلیمان','province_id'=>'13']);
        City::create(['title' => 'مشراگه','province_id'=>'13']);
        City::create(['title' => 'مقاومت','province_id'=>'13']);
        City::create(['title' => 'ملاثانی','province_id'=>'13']);
        City::create(['title' => 'میانرود','province_id'=>'13']);
        City::create(['title' => 'میداود','province_id'=>'13']);
        City::create(['title' => 'مینوشهر','province_id'=>'13']);
        City::create(['title' => 'ویس','province_id'=>'13']);
        City::create(['title' => 'هفتگل','province_id'=>'13']);
        City::create(['title' => 'هندیجان','province_id'=>'13']);
        City::create(['title' => 'هویزه','province_id'=>'13']);
        City::create(['title' => 'ابهر','province_id'=>'14']);
        City::create(['title' => 'ارمغانخانه','province_id'=>'14']);
        City::create(['title' => 'آب بر','province_id'=>'14']);
        City::create(['title' => 'چورزق','province_id'=>'14']);
        City::create(['title' => 'حلب','province_id'=>'14']);
        City::create(['title' => 'خرمدره','province_id'=>'14']);
        City::create(['title' => 'دندی','province_id'=>'14']);
        City::create(['title' => 'زرین آباد','province_id'=>'14']);
        City::create(['title' => 'زرین رود','province_id'=>'14']);
        City::create(['title' => 'زنجان','province_id'=>'14']);
        City::create(['title' => 'سجاس','province_id'=>'14']);
        City::create(['title' => 'سلطانیه','province_id'=>'14']);
        City::create(['title' => 'سهرورد','province_id'=>'14']);
        City::create(['title' => 'صائین قلعه','province_id'=>'14']);
        City::create(['title' => 'قیدار','province_id'=>'14']);
        City::create(['title' => 'گرماب','province_id'=>'14']);
        City::create(['title' => 'ماه نشان','province_id'=>'14']);
        City::create(['title' => 'هیدج','province_id'=>'14']);
        City::create(['title' => 'امیریه','province_id'=>'15']);
        City::create(['title' => 'ایوانکی','province_id'=>'15']);
        City::create(['title' => 'آرادان','province_id'=>'15']);
        City::create(['title' => 'بسطام','province_id'=>'15']);
        City::create(['title' => 'بیارجمند','province_id'=>'15']);
        City::create(['title' => 'دامغان','province_id'=>'15']);
        City::create(['title' => 'درجزین','province_id'=>'15']);
        City::create(['title' => 'دیباج','province_id'=>'15']);
        City::create(['title' => 'سرخه','province_id'=>'15']);
        City::create(['title' => 'سمنان','province_id'=>'15']);
        City::create(['title' => 'شاهرود','province_id'=>'15']);
        City::create(['title' => 'شهمیرزاد','province_id'=>'15']);
        City::create(['title' => 'کلاته خیج','province_id'=>'15']);
        City::create(['title' => 'گرمسار','province_id'=>'15']);
        City::create(['title' => 'مجن','province_id'=>'15']);
        City::create(['title' => 'مهدی شهر','province_id'=>'15']);
        City::create(['title' => 'میامی','province_id'=>'15']);
        City::create(['title' => 'ادیمی','province_id'=>'16']);
        City::create(['title' => 'ایرانشهر','province_id'=>'16']);
        City::create(['title' => 'بزمان','province_id'=>'16']);
        City::create(['title' => 'بمپور','province_id'=>'16']);
        City::create(['title' => 'بنت','province_id'=>'16']);
        City::create(['title' => 'بنجار','province_id'=>'16']);
        City::create(['title' => 'پیشین','province_id'=>'16']);
        City::create(['title' => 'جالق','province_id'=>'16']);
        City::create(['title' => 'چاه بهار','province_id'=>'16']);
        City::create(['title' => 'خاش','province_id'=>'16']);
        City::create(['title' => 'دوست محمد','province_id'=>'16']);
        City::create(['title' => 'راسک','province_id'=>'16']);
        City::create(['title' => 'زابل','province_id'=>'16']);
        City::create(['title' => 'زابلی','province_id'=>'16']);
        City::create(['title' => 'زاهدان','province_id'=>'16']);
        City::create(['title' => 'زرآباد','province_id'=>'16']);
        City::create(['title' => 'زهک','province_id'=>'16']);
        City::create(['title' => 'سراوان','province_id'=>'16']);
        City::create(['title' => 'سیرکان','province_id'=>'16']);
        City::create(['title' => 'علی اکبر','province_id'=>'16']);
        City::create(['title' => 'فنوج','province_id'=>'16']);
        City::create(['title' => 'قصرقند','province_id'=>'16']);
        City::create(['title' => 'کنارک','province_id'=>'16']);
        City::create(['title' => 'گشت','province_id'=>'16']);
        City::create(['title' => 'گلمورتی','province_id'=>'16']);
        City::create(['title' => 'محمدان','province_id'=>'16']);
        City::create(['title' => 'محمدآباد','province_id'=>'16']);
        City::create(['title' => 'محمدی','province_id'=>'16']);
        City::create(['title' => 'میرجاوه','province_id'=>'16']);
        City::create(['title' => 'نصرت آباد','province_id'=>'16']);
        City::create(['title' => 'میرجاوه','province_id'=>'16']);
        City::create(['title' => 'نگور','province_id'=>'16']);
        City::create(['title' => 'نوک آباد','province_id'=>'16']);
        City::create(['title' => 'نیک شهر','province_id'=>'16']);
        City::create(['title' => 'هیدوج','province_id'=>'16']);
        City::create(['title' => 'اردکان','province_id'=>'17']);
        City::create(['title' => 'ارسنجان','province_id'=>'17']);
        City::create(['title' => 'استهبان','province_id'=>'17']);
        City::create(['title' => 'اسیر','province_id'=>'17']);
        City::create(['title' => 'اشکنان','province_id'=>'17']);
        City::create(['title' => 'افزر','province_id'=>'17']);
        City::create(['title' => 'اقلید','province_id'=>'17']);
        City::create(['title' => 'امام شهر','province_id'=>'17']);
        City::create(['title' => 'اوز','province_id'=>'17']);
        City::create(['title' => 'اهل','province_id'=>'17']);
        City::create(['title' => 'ایج','province_id'=>'17']);
        City::create(['title' => 'ایزدخواست','province_id'=>'17']);
        City::create(['title' => 'آباده','province_id'=>'17']);
        City::create(['title' => 'آباده طشک','province_id'=>'17']);
        City::create(['title' => 'باب انار','province_id'=>'17']);
        City::create(['title' => 'بالاده','province_id'=>'17']);
        City::create(['title' => 'بنارویه','province_id'=>'17']);
        City::create(['title' => 'بوانات','province_id'=>'17']);
        City::create(['title' => 'بهمن','province_id'=>'17']);
        City::create(['title' => 'بیرم','province_id'=>'17']);
        City::create(['title' => 'بیضا','province_id'=>'17']);
        City::create(['title' => 'جنت شهر','province_id'=>'17']);
        City::create(['title' => 'جویم','province_id'=>'17']);
        City::create(['title' => 'جهرم','province_id'=>'17']);
        City::create(['title' => 'حاجی آباد','province_id'=>'17']);
        City::create(['title' => 'حسامی','province_id'=>'17']);
        City::create(['title' => 'حسن آباد','province_id'=>'17']);
        City::create(['title' => 'خانه زنیان','province_id'=>'17']);
        City::create(['title' => 'خاوران','province_id'=>'17']);
        City::create(['title' => 'خرامه','province_id'=>'17']);
        City::create(['title' => 'خشت','province_id'=>'17']);
        City::create(['title' => 'خنج','province_id'=>'17']);
        City::create(['title' => 'خور','province_id'=>'17']);
        City::create(['title' => 'خومه زار','province_id'=>'17']);
        City::create(['title' => 'داراب','province_id'=>'17']);
        City::create(['title' => 'داریان','province_id'=>'17']);
        City::create(['title' => 'دبیران','province_id'=>'17']);
        City::create(['title' => 'دژکرد','province_id'=>'17']);
        City::create(['title' => 'دوبرجی','province_id'=>'17']);
        City::create(['title' => 'دوزه','province_id'=>'17']);
        City::create(['title' => 'دهرم','province_id'=>'17']);
        City::create(['title' => 'رامجرد','province_id'=>'17']);
        City::create(['title' => 'رونیز','province_id'=>'17']);
        City::create(['title' => 'زاهدشهر','province_id'=>'17']);
        City::create(['title' => 'زرقان','province_id'=>'17']);
        City::create(['title' => 'سده','province_id'=>'17']);
        City::create(['title' => 'سروستان','province_id'=>'17']);
        City::create(['title' => 'سعادت شهر','province_id'=>'17']);
        City::create(['title' => 'سورمق','province_id'=>'17']);
        City::create(['title' => 'سیدان','province_id'=>'17']);
        City::create(['title' => 'ششده','province_id'=>'17']);
        City::create(['title' => 'شهر جدید صدرا','province_id'=>'17']);
        City::create(['title' => 'شهرپیر','province_id'=>'17']);
        City::create(['title' => 'شیراز','province_id'=>'17']);
        City::create(['title' => 'صغاد','province_id'=>'17']);
        City::create(['title' => 'صفاشهر','province_id'=>'17']);
        City::create(['title' => 'علامرودشت','province_id'=>'17']);
        City::create(['title' => 'عمادده','province_id'=>'17']);
        City::create(['title' => 'فدامی','province_id'=>'17']);
        City::create(['title' => 'فراشبند','province_id'=>'17']);
        City::create(['title' => 'فسا','province_id'=>'17']);
        City::create(['title' => 'فیروزآباد','province_id'=>'17']);
        City::create(['title' => 'قادرآباد','province_id'=>'17']);
        City::create(['title' => 'قطب آباد','province_id'=>'17']);
        City::create(['title' => 'قطرویه','province_id'=>'17']);
        City::create(['title' => 'قیر','province_id'=>'17']);
        City::create(['title' => 'قطرویه','province_id'=>'17']);
        City::create(['title' => 'کارزین','province_id'=>'17']);
        City::create(['title' => 'کازرون','province_id'=>'17']);
        City::create(['title' => 'کامفیروز','province_id'=>'17']);
        City::create(['title' => 'کره ای','province_id'=>'17']);
        City::create(['title' => 'کنارتخته','province_id'=>'17']);
        City::create(['title' => 'کوار','province_id'=>'17']);
        City::create(['title' => 'کوهنجان','province_id'=>'17']);
        City::create(['title' => 'گراش','province_id'=>'17']);
        City::create(['title' => 'گله دار','province_id'=>'17']);
        City::create(['title' => 'لار','province_id'=>'17']);
        City::create(['title' => 'لامرد','province_id'=>'17']);
        City::create(['title' => 'لپوئی','province_id'=>'17']);
        City::create(['title' => 'لطیفی','province_id'=>'17']);
        City::create(['title' => 'مبارک آباد','province_id'=>'17']);
        City::create(['title' => 'مرودشت','province_id'=>'17']);
        City::create(['title' => 'مشکان','province_id'=>'17']);
        City::create(['title' => 'مصیری','province_id'=>'17']);
        City::create(['title' => 'مهر','province_id'=>'17']);
        City::create(['title' => 'میمند','province_id'=>'17']);
        City::create(['title' => 'نوبندگان','province_id'=>'17']);
        City::create(['title' => 'نوجین','province_id'=>'17']);
        City::create(['title' => 'میمند','province_id'=>'17']);
        City::create(['title' => 'نودان','province_id'=>'17']);
        City::create(['title' => 'نورآباد','province_id'=>'17']);
        City::create(['title' => 'نی ریز','province_id'=>'17']);
        City::create(['title' => 'وراوی','province_id'=>'17']);
        City::create(['title' => 'هماشهر','province_id'=>'17']);
        City::create(['title' => 'ارداق','province_id'=>'18']);
        City::create(['title' => 'اسفرورین','province_id'=>'18']);
        City::create(['title' => 'اقبالیه','province_id'=>'18']);
        City::create(['title' => 'الوند','province_id'=>'18']);
        City::create(['title' => 'آبگرم','province_id'=>'18']);
        City::create(['title' => 'آبیک','province_id'=>'18']);
        City::create(['title' => 'آوج','province_id'=>'18']);
        City::create(['title' => 'بوئین زهرا','province_id'=>'18']);
        City::create(['title' => 'بیدستان','province_id'=>'18']);
        City::create(['title' => 'تاکستان','province_id'=>'18']);
        City::create(['title' => 'خاکعلی','province_id'=>'18']);
        City::create(['title' => 'خرمدشت','province_id'=>'18']);
        City::create(['title' => 'دانسفهان','province_id'=>'18']);
        City::create(['title' => 'رازمیان','province_id'=>'18']);
        City::create(['title' => 'سگزآباد','province_id'=>'18']);
        City::create(['title' => 'سیردان','province_id'=>'18']);
        City::create(['title' => 'شال','province_id'=>'18']);
        City::create(['title' => 'شریفیه','province_id'=>'18']);
        City::create(['title' => 'ضیاءآباد','province_id'=>'18']);
        City::create(['title' => 'قزوین','province_id'=>'18']);
        City::create(['title' => 'کوهین','province_id'=>'18']);
        City::create(['title' => 'محمدیه','province_id'=>'18']);
        City::create(['title' => 'محمودآبادنمونه','province_id'=>'18']);
        City::create(['title' => 'معلم کلایه','province_id'=>'18']);
        City::create(['title' => 'نرجه','province_id'=>'18']);
        City::create(['title' => 'جعفریه','province_id'=>'19']);
        City::create(['title' => 'دستجرد','province_id'=>'19']);
        City::create(['title' => 'سلفچگان','province_id'=>'19']);
        City::create(['title' => 'قم','province_id'=>'19']);
        City::create(['title' => 'قنوات','province_id'=>'19']);
        City::create(['title' => 'کهک','province_id'=>'19']);
        City::create(['title' => 'آرمرده','province_id'=>'20']);
        City::create(['title' => 'بابارشانی','province_id'=>'20']);
        City::create(['title' => 'بانه','province_id'=>'20']);
        City::create(['title' => 'بلبان آباد','province_id'=>'20']);
        City::create(['title' => 'بوئین سفلی','province_id'=>'20']);
        City::create(['title' => 'بیجار','province_id'=>'20']);
        City::create(['title' => 'چناره','province_id'=>'20']);
        City::create(['title' => 'دزج','province_id'=>'20']);
        City::create(['title' => 'دلبران','province_id'=>'20']);
        City::create(['title' => 'دهگلان','province_id'=>'20']);
        City::create(['title' => 'دیواندره','province_id'=>'20']);
        City::create(['title' => 'زرینه','province_id'=>'20']);
        City::create(['title' => 'سروآباد','province_id'=>'20']);
        City::create(['title' => 'سریش آباد','province_id'=>'20']);
        City::create(['title' => 'سقز','province_id'=>'20']);
        City::create(['title' => 'سنندج','province_id'=>'20']);
        City::create(['title' => 'شویشه','province_id'=>'20']);
        City::create(['title' => 'صاحب','province_id'=>'20']);
        City::create(['title' => 'قروه','province_id'=>'20']);
        City::create(['title' => 'کامیاران','province_id'=>'20']);
        City::create(['title' => 'کانی دینار','province_id'=>'20']);
        City::create(['title' => 'کانی سور','province_id'=>'20']);
        City::create(['title' => 'مریوان','province_id'=>'20']);
        City::create(['title' => 'موچش','province_id'=>'20']);
        City::create(['title' => 'یاسوکند','province_id'=>'20']);
        City::create(['title' => 'اختیارآباد','province_id'=>'21']);
        City::create(['title' => 'ارزوئیه','province_id'=>'21']);
        City::create(['title' => 'امین شهر','province_id'=>'21']);
        City::create(['title' => 'انار','province_id'=>'21']);
        City::create(['title' => 'اندوهجرد','province_id'=>'21']);
        City::create(['title' => 'باغین','province_id'=>'21']);
        City::create(['title' => 'بافت','province_id'=>'21']);
        City::create(['title' => 'بردسیر','province_id'=>'21']);
        City::create(['title' => 'بروات','province_id'=>'21']);
        City::create(['title' => 'بزنجان','province_id'=>'21']);
        City::create(['title' => 'بم','province_id'=>'21']);
        City::create(['title' => 'بهرمان','province_id'=>'21']);
        City::create(['title' => 'پاریز','province_id'=>'21']);
        City::create(['title' => 'جبالبارز','province_id'=>'21']);
        City::create(['title' => 'جوپار','province_id'=>'21']);
        City::create(['title' => 'جوزم','province_id'=>'21']);
        City::create(['title' => 'جیرفت','province_id'=>'21']);
        City::create(['title' => 'چترود','province_id'=>'21']);
        City::create(['title' => 'خاتون آباد','province_id'=>'21']);
        City::create(['title' => 'خانوک','province_id'=>'21']);
        City::create(['title' => 'خورسند','province_id'=>'21']);
        City::create(['title' => 'درب بهشت','province_id'=>'21']);
        City::create(['title' => 'دوساری','province_id'=>'21']);
        City::create(['title' => 'دهج','province_id'=>'21']);
        City::create(['title' => 'رابر','province_id'=>'21']);
        City::create(['title' => 'راور','province_id'=>'21']);
        City::create(['title' => 'راین','province_id'=>'21']);
        City::create(['title' => 'رفسنجان','province_id'=>'21']);
        City::create(['title' => 'رودبار','province_id'=>'21']);
        City::create(['title' => 'ریحان شهر','province_id'=>'21']);
        City::create(['title' => 'زرند','province_id'=>'21']);
        City::create(['title' => 'زنگی آباد','province_id'=>'21']);
        City::create(['title' => 'زیدآباد','province_id'=>'21']);
        City::create(['title' => 'سرچشمه','province_id'=>'21']);
        City::create(['title' => 'سیرجان','province_id'=>'21']);
        City::create(['title' => 'شهداد','province_id'=>'21']);
        City::create(['title' => 'شهربابک','province_id'=>'21']);
        City::create(['title' => 'صفائیه','province_id'=>'21']);
        City::create(['title' => 'عنبرآباد','province_id'=>'21']);
        City::create(['title' => 'فاریاب','province_id'=>'21']);
        City::create(['title' => 'فهرج','province_id'=>'21']);
        City::create(['title' => 'قلعه گنج','province_id'=>'21']);
        City::create(['title' => 'کاظم آباد','province_id'=>'21']);
        City::create(['title' => 'کرمان','province_id'=>'21']);
        City::create(['title' => 'کشکوئیه','province_id'=>'21']);
        City::create(['title' => 'کوهبنان','province_id'=>'21']);
        City::create(['title' => 'کهنوج','province_id'=>'21']);
        City::create(['title' => 'کیانشهر','province_id'=>'21']);
        City::create(['title' => 'گلباف','province_id'=>'21']);
        City::create(['title' => 'گلزار','province_id'=>'21']);
        City::create(['title' => 'لاله زار','province_id'=>'21']);
        City::create(['title' => 'ماهان','province_id'=>'21']);
        City::create(['title' => 'محمدآباد','province_id'=>'21']);
        City::create(['title' => 'محی آباد','province_id'=>'21']);
        City::create(['title' => 'مردهک','province_id'=>'21']);
        City::create(['title' => 'منوجان','province_id'=>'21']);
        City::create(['title' => 'نجف شهر','province_id'=>'21']);
        City::create(['title' => 'نرماشیر','province_id'=>'21']);
        City::create(['title' => 'نظام شهر','province_id'=>'21']);
        City::create(['title' => 'نگار','province_id'=>'21']);
        City::create(['title' => 'نودژ','province_id'=>'21']);
        City::create(['title' => 'هجدک','province_id'=>'21']);
        City::create(['title' => 'هماشهر','province_id'=>'21']);
        City::create(['title' => 'یزدان شهر','province_id'=>'21']);
        City::create(['title' => 'ازگله','province_id'=>'22']);
        City::create(['title' => 'اسلام آبادغرب','province_id'=>'22']);
        City::create(['title' => 'باینگان','province_id'=>'22']);
        City::create(['title' => 'بیستون','province_id'=>'22']);
        City::create(['title' => 'پاوه','province_id'=>'22']);
        City::create(['title' => 'تازه آباد','province_id'=>'22']);
        City::create(['title' => 'جوانرود','province_id'=>'22']);
        City::create(['title' => 'حمیل','province_id'=>'22']);
        City::create(['title' => 'رباط','province_id'=>'22']);
        City::create(['title' => 'روانسر','province_id'=>'22']);
        City::create(['title' => 'سرپل ذهاب','province_id'=>'22']);
        City::create(['title' => 'سرمست','province_id'=>'22']);
        City::create(['title' => 'سطر','province_id'=>'22']);
        City::create(['title' => 'سنقر','province_id'=>'22']);
        City::create(['title' => 'سومار','province_id'=>'22']);
        City::create(['title' => 'شاهو','province_id'=>'22']);
        City::create(['title' => 'صحنه','province_id'=>'22']);
        City::create(['title' => 'قصرشیرین','province_id'=>'22']);
        City::create(['title' => 'کرمانشاه','province_id'=>'22']);
        City::create(['title' => 'کرندغرب','province_id'=>'22']);
        City::create(['title' => 'کنگاور','province_id'=>'22']);
        City::create(['title' => 'کوزران','province_id'=>'22']);
        City::create(['title' => 'گهواره','province_id'=>'22']);
        City::create(['title' => 'گیلانغرب','province_id'=>'22']);
        City::create(['title' => 'میان راهان','province_id'=>'22']);
        City::create(['title' => 'نودشه','province_id'=>'22']);
        City::create(['title' => 'نوسود','province_id'=>'22']);
        City::create(['title' => 'هرسین','province_id'=>'22']);
        City::create(['title' => 'هلشی','province_id'=>'22']);
        City::create(['title' => 'باشت','province_id'=>'23']);
        City::create(['title' => 'پاتاوه','province_id'=>'23']);
        City::create(['title' => 'چرام','province_id'=>'23']);
        City::create(['title' => 'چیتاب','province_id'=>'23']);
        City::create(['title' => 'دوگنبدان','province_id'=>'23']);
        City::create(['title' => 'دهدشت','province_id'=>'23']);
        City::create(['title' => 'دیشموک','province_id'=>'23']);
        City::create(['title' => 'سوق','province_id'=>'23']);
        City::create(['title' => 'سی سخت','province_id'=>'23']);
        City::create(['title' => 'قلعه رئیسی','province_id'=>'23']);
        City::create(['title' => 'گراب سفلی','province_id'=>'23']);
        City::create(['title' => 'لنده','province_id'=>'23']);
        City::create(['title' => 'لیکک','province_id'=>'23']);
        City::create(['title' => 'مادوان','province_id'=>'23']);
        City::create(['title' => 'مارگون','province_id'=>'23']);
        City::create(['title' => 'یاسوج','province_id'=>'23']);
        City::create(['title' => 'انبارآلوم','province_id'=>'24']);
        City::create(['title' => 'اینچه برون','province_id'=>'24']);
        City::create(['title' => 'آزادشهر','province_id'=>'24']);
        City::create(['title' => 'آق قلا','province_id'=>'24']);
        City::create(['title' => 'بندرگز','province_id'=>'24']);
        City::create(['title' => 'ترکمن','province_id'=>'24']);
        City::create(['title' => 'جلین','province_id'=>'24']);
        City::create(['title' => 'خان ببین','province_id'=>'24']);
        City::create(['title' => 'دلند','province_id'=>'24']);
        City::create(['title' => 'رامیان','province_id'=>'24']);
        City::create(['title' => 'سرخنکلاته','province_id'=>'24']);
        City::create(['title' => 'سیمین شهر','province_id'=>'24']);
        City::create(['title' => 'علی آباد','province_id'=>'24']);
        City::create(['title' => 'فاضل آباد','province_id'=>'24']);
        City::create(['title' => 'کردکوی','province_id'=>'24']);
        City::create(['title' => 'کلاله','province_id'=>'24']);
        City::create(['title' => 'گالیکش','province_id'=>'24']);
        City::create(['title' => 'گرگان','province_id'=>'24']);
        City::create(['title' => 'گمیش تپه','province_id'=>'24']);
        City::create(['title' => 'گنبد کاووس','province_id'=>'24']);
        City::create(['title' => 'مینودشت','province_id'=>'24']);
        City::create(['title' => 'نگین شهر','province_id'=>'24']);
        City::create(['title' => 'نوده خاندوز','province_id'=>'24']);
        City::create(['title' => 'نوکنده','province_id'=>'24']);
        City::create(['title' => 'احمدسرگوراب','province_id'=>'25']);
        City::create(['title' => 'اسالم','province_id'=>'25']);
        City::create(['title' => 'اطاقور','province_id'=>'25']);
        City::create(['title' => 'املش','province_id'=>'25']);
        City::create(['title' => 'آستارا','province_id'=>'25']);
        City::create(['title' => 'آستانه اشرفیه','province_id'=>'25']);
        City::create(['title' => 'بازارجمعه','province_id'=>'25']);
        City::create(['title' => 'بره سر','province_id'=>'25']);
        City::create(['title' => 'توتکابن','province_id'=>'25']);
        City::create(['title' => 'جیرنده','province_id'=>'25']);
        City::create(['title' => 'چابکسر','province_id'=>'25']);
        City::create(['title' => 'چاف وچمخاله','province_id'=>'25']);
        City::create(['title' => 'چوبر','province_id'=>'25']);
        City::create(['title' => 'حویق','province_id'=>'25']);
        City::create(['title' => 'خشکبیجار','province_id'=>'25']);
        City::create(['title' => 'خمام','province_id'=>'25']);
        City::create(['title' => 'دیلمان','province_id'=>'25']);
        City::create(['title' => 'رانکوه','province_id'=>'25']);
        City::create(['title' => 'رحیم آباد','province_id'=>'25']);
        City::create(['title' => 'رستم آباد','province_id'=>'25']);
        City::create(['title' => 'رشت','province_id'=>'25']);
        City::create(['title' => 'رضوانشهر','province_id'=>'25']);
        City::create(['title' => 'رودبار','province_id'=>'25']);
        City::create(['title' => 'رودبنه','province_id'=>'25']);
        City::create(['title' => 'رودسر','province_id'=>'25']);
        City::create(['title' => 'سنگر','province_id'=>'25']);
        City::create(['title' => 'سیاهکل','province_id'=>'25']);
        City::create(['title' => 'شفت','province_id'=>'25']);
        City::create(['title' => 'شلمان','province_id'=>'25']);
        City::create(['title' => 'صومعه سرا','province_id'=>'25']);
        City::create(['title' => 'فومن','province_id'=>'25']);
        City::create(['title' => 'کلاچای','province_id'=>'25']);
        City::create(['title' => 'کوچصفهان','province_id'=>'25']);
        City::create(['title' => 'کومله','province_id'=>'25']);
        City::create(['title' => 'کیاشهر','province_id'=>'25']);
        City::create(['title' => 'گوراب زرمیخ','province_id'=>'25']);
        City::create(['title' => 'لاهیجان','province_id'=>'25']);
        City::create(['title' => 'لشت نشاء','province_id'=>'25']);
        City::create(['title' => 'لنگرود','province_id'=>'25']);
        City::create(['title' => 'لوشان','province_id'=>'25']);
        City::create(['title' => 'لولمان','province_id'=>'25']);
        City::create(['title' => 'لوندویل','province_id'=>'25']);
        City::create(['title' => 'لیسار','province_id'=>'25']);
        City::create(['title' => 'ماسال','province_id'=>'25']);
        City::create(['title' => 'ماسوله','province_id'=>'25']);
        City::create(['title' => 'مرجقل','province_id'=>'25']);
        City::create(['title' => 'منجیل','province_id'=>'25']);
        City::create(['title' => 'واجارگاه','province_id'=>'25']);
        City::create(['title' => 'هشتپر','province_id'=>'25']);
        City::create(['title' => 'ازنا','province_id'=>'26']);
        City::create(['title' => 'اشترینان','province_id'=>'26']);
        City::create(['title' => 'الشتر','province_id'=>'26']);
        City::create(['title' => 'الیگودرز','province_id'=>'26']);
        City::create(['title' => 'بروجرد','province_id'=>'26']);
        City::create(['title' => 'پلدختر','province_id'=>'26']);
        City::create(['title' => 'چالانچولان','province_id'=>'26']);
        City::create(['title' => 'چغلوندی','province_id'=>'26']);
        City::create(['title' => 'چقابل','province_id'=>'26']);
        City::create(['title' => 'خرم آباد','province_id'=>'26']);
        City::create(['title' => 'درب گنبد','province_id'=>'26']);
        City::create(['title' => 'دورود','province_id'=>'26']);
        City::create(['title' => 'زاغه','province_id'=>'26']);
        City::create(['title' => 'سپیددشت','province_id'=>'26']);
        City::create(['title' => 'سراب دوره','province_id'=>'26']);
        City::create(['title' => 'شول آباد','province_id'=>'26']);
        City::create(['title' => 'فیروزآباد','province_id'=>'26']);
        City::create(['title' => 'کونانی','province_id'=>'26']);
        City::create(['title' => 'کوهدشت','province_id'=>'26']);
        City::create(['title' => 'گراب','province_id'=>'26']);
        City::create(['title' => 'معمولان','province_id'=>'26']);
        City::create(['title' => 'مؤمن آباد','province_id'=>'26']);
        City::create(['title' => 'نورآباد','province_id'=>'26']);
        City::create(['title' => 'ویسیان','province_id'=>'26']);
        City::create(['title' => 'هفت چشمه','province_id'=>'26']);
        City::create(['title' => 'امیرکلا','province_id'=>'27']);
        City::create(['title' => 'ایزدشهر','province_id'=>'27']);
        City::create(['title' => 'آلاشت','province_id'=>'27']);
        City::create(['title' => 'آمل','province_id'=>'27']);
        City::create(['title' => 'بابل','province_id'=>'27']);
        City::create(['title' => 'بابلسر','province_id'=>'27']);
        City::create(['title' => 'بلده','province_id'=>'27']);
        City::create(['title' => 'بهشهر','province_id'=>'27']);
        City::create(['title' => 'بهنمیر','province_id'=>'27']);
        City::create(['title' => 'پل سفید','province_id'=>'27']);
        City::create(['title' => 'پول','province_id'=>'27']);
        City::create(['title' => 'تنکابن','province_id'=>'27']);
        City::create(['title' => 'جویبار','province_id'=>'27']);
        City::create(['title' => 'چالوس','province_id'=>'27']);
        City::create(['title' => 'چمستان','province_id'=>'27']);
        City::create(['title' => 'خرم آباد','province_id'=>'27']);
        City::create(['title' => 'خلیل شهر','province_id'=>'27']);
        City::create(['title' => 'خوش رودپی','province_id'=>'27']);
        City::create(['title' => 'دابودشت','province_id'=>'27']);
        City::create(['title' => 'رامسر','province_id'=>'27']);
        City::create(['title' => 'رستمکلا','province_id'=>'27']);
        City::create(['title' => 'رویان','province_id'=>'27']);
        City::create(['title' => 'رینه','province_id'=>'27']);
        City::create(['title' => 'زرگر محله','province_id'=>'27']);
        City::create(['title' => 'زیرآب','province_id'=>'27']);
        City::create(['title' => 'ساری','province_id'=>'27']);
        City::create(['title' => 'سرخرود','province_id'=>'27']);
        City::create(['title' => 'سلمان شهر','province_id'=>'27']);
        City::create(['title' => 'سورک','province_id'=>'27']);
        City::create(['title' => 'شیرگاه','province_id'=>'27']);
        City::create(['title' => 'شیرود','province_id'=>'27']);
        City::create(['title' => 'عباس آباد','province_id'=>'27']);
        City::create(['title' => 'فریدونکنار','province_id'=>'27']);
        City::create(['title' => 'فریم','province_id'=>'27']);
        City::create(['title' => 'قائم شهر','province_id'=>'27']);
        City::create(['title' => 'کتالم وسادات شهر','province_id'=>'27']);
        City::create(['title' => 'کلارآباد','province_id'=>'27']);
        City::create(['title' => 'کلاردشت','province_id'=>'27']);
        City::create(['title' => 'کله بست','province_id'=>'27']);
        City::create(['title' => 'کوهی خیل','province_id'=>'27']);
        City::create(['title' => 'کیاسر','province_id'=>'27']);
        City::create(['title' => 'کیاکلا','province_id'=>'27']);
        City::create(['title' => 'گتاب','province_id'=>'27']);
        City::create(['title' => 'گزنک','province_id'=>'27']);
        City::create(['title' => 'گلوگاه','province_id'=>'27']);
        City::create(['title' => 'محمودآباد','province_id'=>'27']);
        City::create(['title' => 'مرزن آباد','province_id'=>'27']);
        City::create(['title' => 'مرزیکلا','province_id'=>'27']);
        City::create(['title' => 'نشتارود','province_id'=>'27']);
        City::create(['title' => 'نکا','province_id'=>'27']);
        City::create(['title' => 'نور','province_id'=>'27']);
        City::create(['title' => 'نوشهر','province_id'=>'27']);
        City::create(['title' => 'اراک','province_id'=>'28']);
        City::create(['title' => 'آستانه','province_id'=>'28']);
        City::create(['title' => 'آشتیان','province_id'=>'28']);
        City::create(['title' => 'پرندک','province_id'=>'28']);
        City::create(['title' => 'تفرش','province_id'=>'28']);
        City::create(['title' => 'جاورسیان','province_id'=>'28']);
        City::create(['title' => 'خشکرود','province_id'=>'28']);
        City::create(['title' => 'خمین','province_id'=>'28']);
        City::create(['title' => 'خنداب','province_id'=>'28']);
        City::create(['title' => 'داودآباد','province_id'=>'28']);
        City::create(['title' => 'دلیجان','province_id'=>'28']);
        City::create(['title' => 'رازقان','province_id'=>'28']);
        City::create(['title' => 'زاویه','province_id'=>'28']);
        City::create(['title' => 'ساروق','province_id'=>'28']);
        City::create(['title' => 'ساوه','province_id'=>'28']);
        City::create(['title' => 'سنجان','province_id'=>'28']);
        City::create(['title' => 'شازند','province_id'=>'28']);
        City::create(['title' => 'شهرجدیدمهاجران','province_id'=>'28']);
        City::create(['title' => 'فرمهین','province_id'=>'28']);
        City::create(['title' => 'قورچی باشی','province_id'=>'28']);
        City::create(['title' => 'کمیجان','province_id'=>'28']);
        City::create(['title' => 'مأمونیه','province_id'=>'28']);
        City::create(['title' => 'محلات','province_id'=>'28']);
        City::create(['title' => 'میلاجرد','province_id'=>'28']);
        City::create(['title' => 'نراق','province_id'=>'28']);
        City::create(['title' => 'نوبران','province_id'=>'28']);
        City::create(['title' => 'نیمور','province_id'=>'28']);
        City::create(['title' => 'هندودر','province_id'=>'28']);
        City::create(['title' => 'ابوموسی','province_id'=>'29']);
        City::create(['title' => 'بستک','province_id'=>'29']);
        City::create(['title' => 'بندرجاسک','province_id'=>'29']);
        City::create(['title' => 'بندرچارک','province_id'=>'29']);
        City::create(['title' => 'بندرعباس','province_id'=>'29']);
        City::create(['title' => 'بندرلنگه','province_id'=>'29']);
        City::create(['title' => 'پارسیان','province_id'=>'29']);
        City::create(['title' => 'تخت','province_id'=>'29']);
        City::create(['title' => 'جناح','province_id'=>'29']);
        City::create(['title' => 'حاجی آباد','province_id'=>'29']);
        City::create(['title' => 'خمیر','province_id'=>'29']);
        City::create(['title' => 'درگهان','province_id'=>'29']);
        City::create(['title' => 'دهبارز','province_id'=>'29']);
        City::create(['title' => 'رویدر','province_id'=>'29']);
        City::create(['title' => 'زیارتعلی','province_id'=>'29']);
        City::create(['title' => 'سردشت بشاگرد','province_id'=>'29']);
        City::create(['title' => 'سرگز','province_id'=>'29']);
        City::create(['title' => 'سندرک','province_id'=>'29']);
        City::create(['title' => 'سوزا','province_id'=>'29']);
        City::create(['title' => 'سیریک','province_id'=>'29']);
        City::create(['title' => 'فارغان','province_id'=>'29']);
        City::create(['title' => 'فین','province_id'=>'29']);
        City::create(['title' => 'قشم','province_id'=>'29']);
        City::create(['title' => 'قلعه قاضی','province_id'=>'29']);
        City::create(['title' => 'کنگ','province_id'=>'29']);
        City::create(['title' => 'کوشکنار','province_id'=>'29']);
        City::create(['title' => 'کیش','province_id'=>'29']);
        City::create(['title' => 'گوهران','province_id'=>'29']);
        City::create(['title' => 'میناب','province_id'=>'29']);
        City::create(['title' => 'هرمز','province_id'=>'29']);
        City::create(['title' => 'هشتبندی','province_id'=>'29']);
        City::create(['title' => 'ازندریان','province_id'=>'30']);
        City::create(['title' => 'اسدآباد','province_id'=>'30']);
        City::create(['title' => 'برزول','province_id'=>'30']);
        City::create(['title' => 'بهار','province_id'=>'30']);
        City::create(['title' => 'تویسرکان','province_id'=>'30']);
        City::create(['title' => 'جورقان','province_id'=>'30']);
        City::create(['title' => 'جوکار','province_id'=>'30']);
        City::create(['title' => 'دمق','province_id'=>'30']);
        City::create(['title' => 'رزن','province_id'=>'30']);
        City::create(['title' => 'زنگنه','province_id'=>'30']);
        City::create(['title' => 'سامن','province_id'=>'30']);
        City::create(['title' => 'سرکان','province_id'=>'30']);
        City::create(['title' => 'شیرین سو','province_id'=>'30']);
        City::create(['title' => 'صالح آباد','province_id'=>'30']);
        City::create(['title' => 'فامنین','province_id'=>'30']);
        City::create(['title' => 'فرسفج','province_id'=>'30']);
        City::create(['title' => 'فیروزان','province_id'=>'30']);
        City::create(['title' => 'قروه در جزین','province_id'=>'30']);
        City::create(['title' => 'قهاوند','province_id'=>'30']);
        City::create(['title' => 'کبودرآهنگ','province_id'=>'30']);
        City::create(['title' => 'گل تپه','province_id'=>'30']);
        City::create(['title' => 'گیان','province_id'=>'30']);
        City::create(['title' => 'لالجین','province_id'=>'30']);
        City::create(['title' => 'مریانج','province_id'=>'30']);
        City::create(['title' => 'ملایر','province_id'=>'30']);
        City::create(['title' => 'نهاوند','province_id'=>'30']);
        City::create(['title' => 'همدان','province_id'=>'30']);
        City::create(['title' => 'ابرکوه','province_id'=>'31']);
        City::create(['title' => 'احمدآباد','province_id'=>'31']);
        City::create(['title' => 'اردکان','province_id'=>'31']);
        City::create(['title' => 'اشکذر','province_id'=>'31']);
        City::create(['title' => 'بفروئیه','province_id'=>'31']);
        City::create(['title' => 'بهاباد','province_id'=>'31']);
        City::create(['title' => 'تفت','province_id'=>'31']);
        City::create(['title' => 'حمیدیا','province_id'=>'31']);
        City::create(['title' => 'خضرآباد','province_id'=>'31']);
        City::create(['title' => 'دیهوک','province_id'=>'31']);
        City::create(['title' => 'شاهدیه','province_id'=>'31']);
        City::create(['title' => 'عشق آباد','province_id'=>'31']);
        City::create(['title' => 'عقدا','province_id'=>'31']);
        City::create(['title' => 'مروست','province_id'=>'31']);
        City::create(['title' => 'مهردشت','province_id'=>'31']);
        City::create(['title' => 'مهریز','province_id'=>'31']);
        City::create(['title' => 'میبد','province_id'=>'31']);
        City::create(['title' => 'ندوشن','province_id'=>'31']);
        City::create(['title' => 'نیر','province_id'=>'31']);
        City::create(['title' => 'هرات','province_id'=>'31']);
        City::create(['title' => 'یزد','province_id'=>'31']);
    }
}
