<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['title' => 'موسيان','province_id'=>'1']);
        City::create(['title' => 'اسكو','province_id'=>'1']);
        City::create(['title' => 'اهر','province_id'=>'1']);
        City::create(['title' => 'ايلخچي','province_id'=>'1']);
        City::create(['title' => 'آبش احمد','province_id'=>'1']);
        City::create(['title' => 'آذرشهر','province_id'=>'1']);
        City::create(['title' => 'آقكند','province_id'=>'1']);
        City::create(['title' => 'باسمنج','province_id'=>'1']);
        City::create(['title' => 'بخشايش','province_id'=>'1']);
        City::create(['title' => 'بستان آباد','province_id'=>'1']);
        City::create(['title' => 'بناب','province_id'=>'1']);
        City::create(['title' => 'بناب جديد','province_id'=>'1']);
        City::create(['title' => 'تبريز','province_id'=>'1']);
        City::create(['title' => 'ترك','province_id'=>'1']);
        City::create(['title' => 'تركمانچاي','province_id'=>'1']);
        City::create(['title' => 'تسوج','province_id'=>'1']);
        City::create(['title' => 'تيكمه داش','province_id'=>'1']);
        City::create(['title' => 'جلفا','province_id'=>'1']);
        City::create(['title' => 'خاروانا','province_id'=>'1']);
        City::create(['title' => 'خامنه','province_id'=>'1']);
        City::create(['title' => 'خراجو','province_id'=>'1']);
        City::create(['title' => 'خسروشهر','province_id'=>'1']);
        City::create(['title' => 'خمارلو','province_id'=>'1']);
        City::create(['title' => 'خواجه','province_id'=>'1']);
        City::create(['title' => 'دوزدوزان','province_id'=>'1']);
        City::create(['title' => 'زرنق','province_id'=>'1']);
        City::create(['title' => 'زنوز','province_id'=>'1']);
        City::create(['title' => 'سراب','province_id'=>'1']);
        City::create(['title' => 'سردرود','province_id'=>'1']);
        City::create(['title' => 'سيس','province_id'=>'1']);
        City::create(['title' => 'شبستر','province_id'=>'1']);
        City::create(['title' => 'شربيان','province_id'=>'1']);
        City::create(['title' => 'شرفخانه','province_id'=>'1']);
        City::create(['title' => 'شندآباد','province_id'=>'1']);
        City::create(['title' => 'شهرجديدسهند','province_id'=>'1']);
        City::create(['title' => 'صوفيان','province_id'=>'1']);
        City::create(['title' => 'عجب شير','province_id'=>'1']);
        City::create(['title' => 'قره آغاج','province_id'=>'1']);
        City::create(['title' => 'كشكسراي','province_id'=>'1']);
        City::create(['title' => 'كلوانق','province_id'=>'1']);
        City::create(['title' => 'كليبر','province_id'=>'1']);
        City::create(['title' => 'كوزه كنان','province_id'=>'1']);
        City::create(['title' => 'گوگان','province_id'=>'1']);
        City::create(['title' => 'ليلان','province_id'=>'1']);
        City::create(['title' => 'مراغه','province_id'=>'1']);
        City::create(['title' => 'مرند','province_id'=>'1']);
        City::create(['title' => 'ملكان','province_id'=>'1']);
        City::create(['title' => 'ممقان','province_id'=>'1']);
        City::create(['title' => 'مهربان','province_id'=>'1']);
        City::create(['title' => 'ميانه','province_id'=>'1']);
        City::create(['title' => 'نظركهريزي','province_id'=>'1']);
        City::create(['title' => 'وايقان','province_id'=>'1']);
        City::create(['title' => 'ورزقان','province_id'=>'1']);
        City::create(['title' => 'هاديشهر','province_id'=>'1']);
        City::create(['title' => 'هريس','province_id'=>'1']);
        City::create(['title' => 'هشترود','province_id'=>'1']);
        City::create(['title' => 'هوراند','province_id'=>'1']);
        City::create(['title' => 'يامچي','province_id'=>'1']);
        City::create(['title' => 'اروميه','province_id'=>'2']);
        City::create(['title' => 'اشنويه','province_id'=>'2']);
        City::create(['title' => 'ايواوغلي','province_id'=>'2']);
        City::create(['title' => 'آواجيق','province_id'=>'2']);
        City::create(['title' => 'باروق','province_id'=>'2']);
        City::create(['title' => 'بازرگان','province_id'=>'2']);
        City::create(['title' => 'بوكان','province_id'=>'2']);
        City::create(['title' => 'پلدشت','province_id'=>'2']);
        City::create(['title' => 'پيرانشهر','province_id'=>'2']);
        City::create(['title' => 'تازه شهر','province_id'=>'2']);
        City::create(['title' => 'تكاب','province_id'=>'2']);
        City::create(['title' => 'چهاربرج','province_id'=>'2']);
        City::create(['title' => 'خليفان','province_id'=>'2']);
        City::create(['title' => 'خوي','province_id'=>'2']);
        City::create(['title' => 'ديزج ديز','province_id'=>'2']);
        City::create(['title' => 'ربط','province_id'=>'2']);
        City::create(['title' => 'سردشت','province_id'=>'2']);
        City::create(['title' => 'سرو','province_id'=>'2']);
        City::create(['title' => 'سلماس','province_id'=>'2']);
        City::create(['title' => 'سيلوانه','province_id'=>'2']);
        City::create(['title' => 'سيمينه','province_id'=>'2']);
        City::create(['title' => 'سيه چشمه','province_id'=>'2']);
        City::create(['title' => 'شاهين دژ','province_id'=>'2']);
        City::create(['title' => 'شوط','province_id'=>'2']);
        City::create(['title' => 'فيرورق','province_id'=>'2']);
        City::create(['title' => 'قره ضياءالدين','province_id'=>'2']);
        City::create(['title' => 'قطور','province_id'=>'2']);
        City::create(['title' => 'قوشچي','province_id'=>'2']);
        City::create(['title' => 'كشاورز','province_id'=>'2']);
        City::create(['title' => 'گردكشانه','province_id'=>'2']);
        City::create(['title' => 'ماكو','province_id'=>'2']);
        City::create(['title' => 'محمديار','province_id'=>'2']);
        City::create(['title' => 'محمودآباد','province_id'=>'2']);
        City::create(['title' => 'مهاباد','province_id'=>'2']);
        City::create(['title' => 'مياندوآب','province_id'=>'2']);
        City::create(['title' => 'ميرآباد','province_id'=>'2']);
        City::create(['title' => 'نالوس','province_id'=>'2']);
        City::create(['title' => 'نقده','province_id'=>'2']);
        City::create(['title' => 'نوشين','province_id'=>'2']);
        City::create(['title' => 'اردبيل','province_id'=>'3']);
        City::create(['title' => 'اصلاندوز','province_id'=>'3']);
        City::create(['title' => 'آبي بيگلو','province_id'=>'3']);
        City::create(['title' => 'بيله سوار','province_id'=>'3']);
        City::create(['title' => 'پارس آباد','province_id'=>'3']);
        City::create(['title' => 'تازه كند','province_id'=>'3']);
        City::create(['title' => 'تازه كندانگوت','province_id'=>'3']);
        City::create(['title' => 'جعفرآباد','province_id'=>'3']);
        City::create(['title' => 'خلخال','province_id'=>'3']);
        City::create(['title' => 'رضي','province_id'=>'3']);
        City::create(['title' => 'سرعين','province_id'=>'3']);
        City::create(['title' => 'عنبران','province_id'=>'3']);
        City::create(['title' => 'فخرآباد','province_id'=>'3']);
        City::create(['title' => 'كلور','province_id'=>'3']);
        City::create(['title' => 'گيوي','province_id'=>'3']);
        City::create(['title' => 'لاهرود','province_id'=>'3']);
        City::create(['title' => 'مرادلو','province_id'=>'3']);
        City::create(['title' => 'مشگين شهر','province_id'=>'3']);
        City::create(['title' => 'نمين','province_id'=>'3']);
        City::create(['title' => 'نير','province_id'=>'3']);
        City::create(['title' => 'هشتجين','province_id'=>'3']);
        City::create(['title' => 'هير','province_id'=>'3']);
        City::create(['title' => 'ابريشم','province_id'=>'4']);
        City::create(['title' => 'ابوزيدآباد','province_id'=>'4']);
        City::create(['title' => 'اردستان','province_id'=>'4']);
        City::create(['title' => 'اصفهان','province_id'=>'4']);
        City::create(['title' => 'افوس','province_id'=>'4']);
        City::create(['title' => 'انارك','province_id'=>'4']);
        City::create(['title' => 'ايمانشهر','province_id'=>'4']);
        City::create(['title' => 'آران وبيدگل','province_id'=>'4']);
        City::create(['title' => 'بادرود','province_id'=>'4']);
        City::create(['title' => 'باغ بهادران','province_id'=>'4']);
        City::create(['title' => 'بافران','province_id'=>'4']);
        City::create(['title' => 'برزك','province_id'=>'4']);
        City::create(['title' => 'برف انبار','province_id'=>'4']);
        City::create(['title' => 'بوئين ومياندشت','province_id'=>'4']);
        City::create(['title' => 'بهاران شهر','province_id'=>'4']);
        City::create(['title' => 'بهارستان','province_id'=>'4']);
        City::create(['title' => 'پيربكران','province_id'=>'4']);
        City::create(['title' => 'تودشك','province_id'=>'4']);
        City::create(['title' => 'تيران','province_id'=>'4']);
        City::create(['title' => 'جندق','province_id'=>'4']);
        City::create(['title' => 'جوزدان','province_id'=>'4']);
        City::create(['title' => 'جوشقان وكامو','province_id'=>'4']);
        City::create(['title' => 'چادگان','province_id'=>'4']);
        City::create(['title' => 'چرمهين','province_id'=>'4']);
        City::create(['title' => 'چمگردان','province_id'=>'4']);
        City::create(['title' => 'حبيب آباد','province_id'=>'4']);
        City::create(['title' => 'حسن آباد','province_id'=>'4']);
        City::create(['title' => 'چمگردان','province_id'=>'4']);
        City::create(['title' => 'حنا','province_id'=>'4']);
        City::create(['title' => 'خالدآباد','province_id'=>'4']);
        City::create(['title' => 'خميني شهر','province_id'=>'4']);
        City::create(['title' => 'خوانسار','province_id'=>'4']);
        City::create(['title' => 'خور','province_id'=>'4']);
        City::create(['title' => 'خوراسگان','province_id'=>'4']);
        City::create(['title' => 'خورزوق','province_id'=>'4']);
        City::create(['title' => 'داران','province_id'=>'4']);
        City::create(['title' => 'دامنه','province_id'=>'4']);
        City::create(['title' => 'درچه پياز','province_id'=>'4']);
        City::create(['title' => 'دستگرد','province_id'=>'4']);
        City::create(['title' => 'دولت آباد','province_id'=>'4']);
        City::create(['title' => 'دهاقان','province_id'=>'4']);
        City::create(['title' => 'دهق','province_id'=>'4']);
        City::create(['title' => 'ديزيچه','province_id'=>'4']);
        City::create(['title' => 'رزوه','province_id'=>'4']);
        City::create(['title' => 'رضوانشهر','province_id'=>'4']);
        City::create(['title' => 'زاينده رود','province_id'=>'4']);
        City::create(['title' => 'زرين شهر','province_id'=>'4']);
        City::create(['title' => 'زواره','province_id'=>'4']);
        City::create(['title' => 'زيباشهر','province_id'=>'4']);
        City::create(['title' => 'سده لنجان','province_id'=>'4']);
        City::create(['title' => 'سفيدشهر','province_id'=>'4']);
        City::create(['title' => 'سگزي','province_id'=>'4']);
        City::create(['title' => 'سميرم','province_id'=>'4']);
        City::create(['title' => 'شاپورآباد','province_id'=>'4']);
        City::create(['title' => 'شاهين شهر','province_id'=>'4']);
        City::create(['title' => 'شهرضا','province_id'=>'4']);
        City::create(['title' => 'طالخونچه','province_id'=>'4']);
        City::create(['title' => 'عسگران','province_id'=>'4']);
        City::create(['title' => 'علويچه','province_id'=>'4']);
        City::create(['title' => 'فرخي','province_id'=>'4']);
        City::create(['title' => 'فريدونشهر','province_id'=>'4']);
        City::create(['title' => 'فلاورجان','province_id'=>'4']);
        City::create(['title' => 'فولادشهر','province_id'=>'4']);
        City::create(['title' => 'قمصر','province_id'=>'4']);
        City::create(['title' => 'قهجاورستان','province_id'=>'4']);
        City::create(['title' => 'قهدريجان','province_id'=>'4']);
        City::create(['title' => 'كاشان','province_id'=>'4']);
        City::create(['title' => 'كركوند','province_id'=>'4']);
        City::create(['title' => 'كليشادوسودرجان','province_id'=>'4']);
        City::create(['title' => 'كمشچه','province_id'=>'4']);
        City::create(['title' => 'كمه','province_id'=>'4']);
        City::create(['title' => 'كوشك','province_id'=>'4']);
        City::create(['title' => 'كوهپايه','province_id'=>'4']);
        City::create(['title' => 'كهريزسنگ','province_id'=>'4']);
        City::create(['title' => 'گرگاب','province_id'=>'4']);
        City::create(['title' => 'گزبرخوار','province_id'=>'4']);
        City::create(['title' => 'گلپايگان','province_id'=>'4']);
        City::create(['title' => 'گلدشت','province_id'=>'4']);
        City::create(['title' => 'گلشن','province_id'=>'4']);
        City::create(['title' => 'گلشهر','province_id'=>'4']);
        City::create(['title' => 'گوگد','province_id'=>'4']);
        City::create(['title' => 'لاي بيد','province_id'=>'4']);
        City::create(['title' => 'مباركه','province_id'=>'4']);
        City::create(['title' => 'محمدآباد','province_id'=>'4']);
        City::create(['title' => 'مشكات','province_id'=>'4']);
        City::create(['title' => 'منظريه','province_id'=>'4']);
        City::create(['title' => 'مهاباد','province_id'=>'4']);
        City::create(['title' => 'ميمه','province_id'=>'4']);
        City::create(['title' => 'نائين','province_id'=>'4']);
        City::create(['title' => 'نجف آباد','province_id'=>'4']);
        City::create(['title' => 'نوش آباد','province_id'=>'4']);
        City::create(['title' => 'نياسر','province_id'=>'4']);
        City::create(['title' => 'نيك آباد','province_id'=>'4']);
        City::create(['title' => 'ورزنه','province_id'=>'4']);
        City::create(['title' => 'ورنامخواست','province_id'=>'4']);
        City::create(['title' => 'وزوان','province_id'=>'4']);
        City::create(['title' => 'ونك','province_id'=>'4']);
        City::create(['title' => 'هرند','province_id'=>'4']);
        City::create(['title' => 'اشتهارد','province_id'=>'5']);
        City::create(['title' => 'آسارا','province_id'=>'5']);
        City::create(['title' => 'تنكمان','province_id'=>'5']);
        City::create(['title' => 'چهارباغ','province_id'=>'5']);
        City::create(['title' => 'سيف آباد','province_id'=>'5']);
        City::create(['title' => 'شهرجديدهشتگرد','province_id'=>'5']);
        City::create(['title' => 'طالقان','province_id'=>'5']);
        City::create(['title' => 'كرج','province_id'=>'5']);
        City::create(['title' => 'كمال شهر','province_id'=>'5']);
        City::create(['title' => 'كوهسار','province_id'=>'5']);
        City::create(['title' => 'گرمدره','province_id'=>'5']);
        City::create(['title' => 'ماهدشت','province_id'=>'5']);
        City::create(['title' => 'محمدشهر','province_id'=>'5']);
        City::create(['title' => 'مشكين دشت','province_id'=>'5']);
        City::create(['title' => 'نظرآباد','province_id'=>'5']);
        City::create(['title' => 'هشتگرد','province_id'=>'5']);
        City::create(['title' => 'اركواز','province_id'=>'6']);
        City::create(['title' => 'ايلام','province_id'=>'6']);
        City::create(['title' => 'ايوان','province_id'=>'6']);
        City::create(['title' => 'آبدانان','province_id'=>'6']);
        City::create(['title' => 'آسمان آباد','province_id'=>'6']);
        City::create(['title' => 'پهله','province_id'=>'6']);
        City::create(['title' => 'توحيد','province_id'=>'6']);
        City::create(['title' => 'چوار','province_id'=>'6']);
        City::create(['title' => 'دره شهر','province_id'=>'6']);
        City::create(['title' => 'دلگشا','province_id'=>'6']);
        City::create(['title' => 'دهلران','province_id'=>'6']);
        City::create(['title' => 'زرنه','province_id'=>'6']);
        City::create(['title' => 'سراب باغ','province_id'=>'6']);
        City::create(['title' => 'سرابله','province_id'=>'6']);
        City::create(['title' => 'صالح آباد','province_id'=>'6']);
        City::create(['title' => 'لومار','province_id'=>'6']);
        City::create(['title' => 'مورموري','province_id'=>'6']);
        City::create(['title' => 'موسيان','province_id'=>'6']);
        City::create(['title' => 'مهران','province_id'=>'6']);
        City::create(['title' => 'ميمه','province_id'=>'6']);
        City::create(['title' => 'امام حسن','province_id'=>'7']);
        City::create(['title' => 'انارستان','province_id'=>'7']);
        City::create(['title' => 'اهرم','province_id'=>'7']);
        City::create(['title' => 'آبپخش','province_id'=>'7']);
        City::create(['title' => 'آبدان','province_id'=>'7']);
        City::create(['title' => 'برازجان','province_id'=>'7']);
        City::create(['title' => 'بردخون','province_id'=>'7']);
        City::create(['title' => 'بردستان','province_id'=>'7']);
        City::create(['title' => 'بندردير','province_id'=>'7']);
        City::create(['title' => 'بندرديلم','province_id'=>'7']);
        City::create(['title' => 'بندرريگ','province_id'=>'7']);
        City::create(['title' => 'بندركنگان','province_id'=>'7']);
        City::create(['title' => 'بندرگناوه','province_id'=>'7']);
        City::create(['title' => 'بنك','province_id'=>'7']);
        City::create(['title' => 'بوشهر','province_id'=>'7']);
        City::create(['title' => 'تنگ ارم','province_id'=>'7']);
        City::create(['title' => 'جم','province_id'=>'7']);
        City::create(['title' => 'چغادك','province_id'=>'7']);
        City::create(['title' => 'خارك','province_id'=>'7']);
        City::create(['title' => 'خورموج','province_id'=>'7']);
        City::create(['title' => 'دالكي','province_id'=>'7']);
        City::create(['title' => 'دلوار','province_id'=>'7']);
        City::create(['title' => 'ريز','province_id'=>'7']);
        City::create(['title' => 'سعدآباد','province_id'=>'7']);
        City::create(['title' => 'سيراف','province_id'=>'7']);
        City::create(['title' => 'شبانكاره','province_id'=>'7']);
        City::create(['title' => 'شنبه','province_id'=>'7']);
        City::create(['title' => 'عسلويه','province_id'=>'7']);
        City::create(['title' => 'كاكي','province_id'=>'7']);
        City::create(['title' => 'كلمه','province_id'=>'7']);
        City::create(['title' => 'نخل تقي','province_id'=>'7']);
        City::create(['title' => 'وحدتيه','province_id'=>'7']);
        City::create(['title' => 'ارجمند','province_id'=>'8']);
        City::create(['title' => 'اسلامشهر','province_id'=>'8']);
        City::create(['title' => 'انديشه','province_id'=>'8']);
        City::create(['title' => 'آبسرد','province_id'=>'8']);
        City::create(['title' => 'آبعلي','province_id'=>'8']);
        City::create(['title' => 'باغستان','province_id'=>'8']);
        City::create(['title' => 'باقرشهر','province_id'=>'8']);
        City::create(['title' => 'بومهن','province_id'=>'8']);
        City::create(['title' => 'پاكدشت','province_id'=>'8']);
        City::create(['title' => 'پرديس','province_id'=>'8']);
        City::create(['title' => 'پيشوا','province_id'=>'8']);
        City::create(['title' => 'تهران','province_id'=>'8']);
        City::create(['title' => 'جوادآباد','province_id'=>'8']);
        City::create(['title' => 'چهاردانگه','province_id'=>'8']);
        City::create(['title' => 'حسن آباد','province_id'=>'8']);
        City::create(['title' => 'دماوند','province_id'=>'8']);
        City::create(['title' => 'حسن آباد','province_id'=>'8']);
        City::create(['title' => 'رباط كريم','province_id'=>'8']);
        City::create(['title' => 'رودهن','province_id'=>'8']);
        City::create(['title' => 'ري','province_id'=>'8']);
        City::create(['title' => 'شاهدشهر','province_id'=>'8']);
        City::create(['title' => 'شريف آباد','province_id'=>'8']);
        City::create(['title' => 'شهريار','province_id'=>'8']);
        City::create(['title' => 'صالح آباد','province_id'=>'8']);
        City::create(['title' => 'صباشهر','province_id'=>'8']);
        City::create(['title' => 'صفادشت','province_id'=>'8']);
        City::create(['title' => 'صباشهر','province_id'=>'8']);
        City::create(['title' => 'فردوسيه','province_id'=>'8']);
        City::create(['title' => 'فرون آباد','province_id'=>'8']);
        City::create(['title' => 'فشم','province_id'=>'8']);
        City::create(['title' => 'فيروزكوه','province_id'=>'8']);
        City::create(['title' => 'قدس','province_id'=>'8']);
        City::create(['title' => 'قرچك','province_id'=>'8']);
        City::create(['title' => 'كهريزك','province_id'=>'8']);
        City::create(['title' => 'كيلان','province_id'=>'8']);
        City::create(['title' => 'گلستان','province_id'=>'8']);
        City::create(['title' => 'لواسان','province_id'=>'8']);
        City::create(['title' => 'ملارد','province_id'=>'8']);
        City::create(['title' => 'نسيم شهر','province_id'=>'8']);
        City::create(['title' => 'نصيرآباد','province_id'=>'8']);
        City::create(['title' => 'وحيديه','province_id'=>'8']);
        City::create(['title' => 'ورامين','province_id'=>'8']);
        City::create(['title' => 'اردل','province_id'=>'9']);
        City::create(['title' => 'آلوني','province_id'=>'9']);
        City::create(['title' => 'باباحيدر','province_id'=>'9']);
        City::create(['title' => 'بروجن','province_id'=>'9']);
        City::create(['title' => 'بلداجي','province_id'=>'9']);
        City::create(['title' => 'بن','province_id'=>'9']);
        City::create(['title' => 'جونقان','province_id'=>'9']);
        City::create(['title' => 'چلگرد','province_id'=>'9']);
        City::create(['title' => 'سامان','province_id'=>'9']);
        City::create(['title' => 'سفيددشت','province_id'=>'9']);
        City::create(['title' => 'سودجان','province_id'=>'9']);
        City::create(['title' => 'سورشجان','province_id'=>'9']);
        City::create(['title' => 'شلمزار','province_id'=>'9']);
        City::create(['title' => 'شهركرد','province_id'=>'9']);
        City::create(['title' => 'طاقانك','province_id'=>'9']);
        City::create(['title' => 'فارسان','province_id'=>'9']);
        City::create(['title' => 'فرادنبه','province_id'=>'9']);
        City::create(['title' => 'فرخ شهر','province_id'=>'9']);
        City::create(['title' => 'كيان','province_id'=>'9']);
        City::create(['title' => 'گندمان','province_id'=>'9']);
        City::create(['title' => 'گهرو','province_id'=>'9']);
        City::create(['title' => 'لردگان','province_id'=>'9']);
        City::create(['title' => 'مال خليفه','province_id'=>'9']);
        City::create(['title' => 'ناغان','province_id'=>'9']);
        City::create(['title' => 'نافچ','province_id'=>'9']);
        City::create(['title' => 'نقنه','province_id'=>'9']);
        City::create(['title' => 'هفشجان','province_id'=>'9']);
        City::create(['title' => 'ارسك','province_id'=>'10']);
        City::create(['title' => 'اسديه','province_id'=>'10']);
        City::create(['title' => 'اسفدن','province_id'=>'10']);
        City::create(['title' => 'اسلاميه','province_id'=>'10']);
        City::create(['title' => 'آرين شهر','province_id'=>'10']);
        City::create(['title' => 'آيسك','province_id'=>'10']);
        City::create(['title' => 'بشرويه','province_id'=>'10']);
        City::create(['title' => 'بيرجند','province_id'=>'10']);
        City::create(['title' => 'حاجي آباد','province_id'=>'10']);
        City::create(['title' => 'خضري دشت بياض','province_id'=>'10']);
        City::create(['title' => 'خوسف','province_id'=>'10']);
        City::create(['title' => 'زهان','province_id'=>'10']);
        City::create(['title' => 'سرايان','province_id'=>'10']);
        City::create(['title' => 'سربيشه','province_id'=>'10']);
        City::create(['title' => 'سه قلعه','province_id'=>'10']);
        City::create(['title' => 'شوسف','province_id'=>'10']);
        City::create(['title' => 'طبس مسينا','province_id'=>'10']);
        City::create(['title' => 'فردوس','province_id'=>'10']);
        City::create(['title' => 'قائن','province_id'=>'10']);
        City::create(['title' => 'قهستان','province_id'=>'10']);
        City::create(['title' => 'گزيك','province_id'=>'10']);
        City::create(['title' => 'محمدشهر','province_id'=>'10']);
        City::create(['title' => 'مود','province_id'=>'10']);
        City::create(['title' => 'نهبندان','province_id'=>'10']);
        City::create(['title' => 'نيمبلوك','province_id'=>'10']);
        City::create(['title' => 'احمدآبادصولت','province_id'=>'11']);
        City::create(['title' => 'انابد','province_id'=>'11']);
        City::create(['title' => 'باجگيران','province_id'=>'11']);
        City::create(['title' => 'باخرز','province_id'=>'11']);
        City::create(['title' => 'بار','province_id'=>'11']);
        City::create(['title' => 'بايگ','province_id'=>'11']);
        City::create(['title' => 'بجستان','province_id'=>'11']);
        City::create(['title' => 'بردسكن','province_id'=>'11']);
        City::create(['title' => 'بيدخت','province_id'=>'11']);
        City::create(['title' => 'تايباد','province_id'=>'11']);
        City::create(['title' => 'تربت جام','province_id'=>'11']);
        City::create(['title' => 'تربت حيدريه','province_id'=>'11']);
        City::create(['title' => 'جغتاي','province_id'=>'11']);
        City::create(['title' => 'جنگل','province_id'=>'11']);
        City::create(['title' => 'چاپشلو','province_id'=>'11']);
        City::create(['title' => 'چكنه','province_id'=>'11']);
        City::create(['title' => 'چناران','province_id'=>'11']);
        City::create(['title' => 'خرو','province_id'=>'11']);
        City::create(['title' => 'خليل آباد','province_id'=>'11']);
        City::create(['title' => 'خواف','province_id'=>'11']);
        City::create(['title' => 'داورزن','province_id'=>'11']);
        City::create(['title' => 'درگز','province_id'=>'11']);
        City::create(['title' => 'درود','province_id'=>'11']);
        City::create(['title' => 'دولت آباد','province_id'=>'11']);
        City::create(['title' => 'رباط سنگ','province_id'=>'11']);
        City::create(['title' => 'رشتخوار','province_id'=>'11']);
        City::create(['title' => 'رضويه','province_id'=>'11']);
        City::create(['title' => 'روداب','province_id'=>'11']);
        City::create(['title' => 'ريوش','province_id'=>'11']);
        City::create(['title' => 'سبزوار','province_id'=>'11']);
        City::create(['title' => 'سرخس','province_id'=>'11']);
        City::create(['title' => 'سفيدسنگ','province_id'=>'11']);
        City::create(['title' => 'سلامي','province_id'=>'11']);
        City::create(['title' => 'سلطان آباد','province_id'=>'11']);
        City::create(['title' => 'سنگان','province_id'=>'11']);
        City::create(['title' => 'شادمهر','province_id'=>'11']);
        City::create(['title' => 'شانديز','province_id'=>'11']);
        City::create(['title' => 'ششتمد','province_id'=>'11']);
        City::create(['title' => 'شهرآباد','province_id'=>'11']);
        City::create(['title' => 'شهرزو','province_id'=>'11']);
        City::create(['title' => 'صالح آباد','province_id'=>'11']);
        City::create(['title' => 'طرقبه','province_id'=>'11']);
        City::create(['title' => 'عشق آباد','province_id'=>'11']);
        City::create(['title' => 'فرهادگرد','province_id'=>'11']);
        City::create(['title' => 'فريمان','province_id'=>'11']);
        City::create(['title' => 'فيروزه','province_id'=>'11']);
        City::create(['title' => 'فيض آباد','province_id'=>'11']);
        City::create(['title' => 'قاسم آباد','province_id'=>'11']);
        City::create(['title' => 'قدمگاه','province_id'=>'11']);
        City::create(['title' => 'قلندرآباد','province_id'=>'11']);
        City::create(['title' => 'قوچان','province_id'=>'11']);
        City::create(['title' => 'كاخك','province_id'=>'11']);
        City::create(['title' => 'كاريز','province_id'=>'11']);
        City::create(['title' => 'كاشمر','province_id'=>'11']);
        City::create(['title' => 'كدكن','province_id'=>'11']);
        City::create(['title' => 'كلات','province_id'=>'11']);
        City::create(['title' => 'كندر','province_id'=>'11']);
        City::create(['title' => 'گلمكان','province_id'=>'11']);
        City::create(['title' => 'گناباد','province_id'=>'11']);
        City::create(['title' => 'لطف آباد','province_id'=>'11']);
        City::create(['title' => 'مزدآوند','province_id'=>'11']);
        City::create(['title' => 'مشهد','province_id'=>'11']);
        City::create(['title' => 'ملك آباد','province_id'=>'11']);
        City::create(['title' => 'نشتيفان','province_id'=>'11']);
        City::create(['title' => 'نصرآباد','province_id'=>'11']);
        City::create(['title' => 'نقاب','province_id'=>'11']);
        City::create(['title' => 'نوخندان','province_id'=>'11']);
        City::create(['title' => 'نيشابور','province_id'=>'11']);
        City::create(['title' => 'نيل شهر','province_id'=>'11']);
        City::create(['title' => 'همت آباد','province_id'=>'11']);
        City::create(['title' => 'يونسي','province_id'=>'11']);
        City::create(['title' => 'اسفراين','province_id'=>'12']);
        City::create(['title' => 'ايور','province_id'=>'12']);
        City::create(['title' => 'آشخانه','province_id'=>'12']);
        City::create(['title' => 'بجنورد','province_id'=>'12']);
        City::create(['title' => 'پيش قلعه','province_id'=>'12']);
        City::create(['title' => 'تيتكانلو','province_id'=>'12']);
        City::create(['title' => 'جاجرم','province_id'=>'12']);
        City::create(['title' => 'حصارگرمخان','province_id'=>'12']);
        City::create(['title' => 'درق','province_id'=>'12']);
        City::create(['title' => 'راز','province_id'=>'12']);
        City::create(['title' => 'سنخواست','province_id'=>'12']);
        City::create(['title' => 'شوقان','province_id'=>'12']);
        City::create(['title' => 'شيروان','province_id'=>'12']);
        City::create(['title' => 'صفي آباد','province_id'=>'12']);
        City::create(['title' => 'فاروج','province_id'=>'12']);
        City::create(['title' => 'قاضي','province_id'=>'12']);
        City::create(['title' => 'گرمه','province_id'=>'12']);
        City::create(['title' => 'لوجلي','province_id'=>'12']);
        City::create(['title' => 'اروندكنار','province_id'=>'13']);
        City::create(['title' => 'الوان','province_id'=>'13']);
        City::create(['title' => 'اميديه','province_id'=>'13']);
        City::create(['title' => 'انديمشك','province_id'=>'13']);
        City::create(['title' => 'اهواز','province_id'=>'13']);
        City::create(['title' => 'ايذه','province_id'=>'13']);
        City::create(['title' => 'آبادان','province_id'=>'13']);
        City::create(['title' => 'آغاجاري','province_id'=>'13']);
        City::create(['title' => 'باغ ملك','province_id'=>'13']);
        City::create(['title' => 'بستان','province_id'=>'13']);
        City::create(['title' => 'بندرامام خميني','province_id'=>'13']);
        City::create(['title' => 'بندرماهشهر','province_id'=>'13']);
        City::create(['title' => 'بهبهان','province_id'=>'13']);
        City::create(['title' => 'تركالكي','province_id'=>'13']);
        City::create(['title' => 'جايزان','province_id'=>'13']);
        City::create(['title' => 'جنت مكان','province_id'=>'13']);
        City::create(['title' => 'چغاميش','province_id'=>'13']);
        City::create(['title' => 'چمران','province_id'=>'13']);
        City::create(['title' => 'چوئبده','province_id'=>'13']);
        City::create(['title' => 'حسينيه','province_id'=>'13']);
        City::create(['title' => 'حمزه','province_id'=>'13']);
        City::create(['title' => 'حميديه','province_id'=>'13']);
        City::create(['title' => 'خرمشهر','province_id'=>'13']);
        City::create(['title' => 'دارخوين','province_id'=>'13']);
        City::create(['title' => 'دزآب','province_id'=>'13']);
        City::create(['title' => 'دزفول','province_id'=>'13']);
        City::create(['title' => 'دهدز','province_id'=>'13']);
        City::create(['title' => 'رامشير','province_id'=>'13']);
        City::create(['title' => 'رامهرمز','province_id'=>'13']);
        City::create(['title' => 'رفيع','province_id'=>'13']);
        City::create(['title' => 'زهره','province_id'=>'13']);
        City::create(['title' => 'سالند','province_id'=>'13']);
        City::create(['title' => 'سردشت','province_id'=>'13']);
        City::create(['title' => 'سماله','province_id'=>'13']);
        City::create(['title' => 'سوسنگرد','province_id'=>'13']);
        City::create(['title' => 'شادگان','province_id'=>'13']);
        City::create(['title' => 'شاوور','province_id'=>'13']);
        City::create(['title' => 'شرافت','province_id'=>'13']);
        City::create(['title' => 'شوش','province_id'=>'13']);
        City::create(['title' => 'شوشتر','province_id'=>'13']);
        City::create(['title' => 'شيبان','province_id'=>'13']);
        City::create(['title' => 'صالح شهر','province_id'=>'13']);
        City::create(['title' => 'صالح مشطط','province_id'=>'13']);
        City::create(['title' => 'صفي آباد','province_id'=>'13']);
        City::create(['title' => 'صيدون','province_id'=>'13']);
        City::create(['title' => 'قلعه تل','province_id'=>'13']);
        City::create(['title' => 'قلعه خواجه','province_id'=>'13']);
        City::create(['title' => 'گتوند','province_id'=>'13']);
        City::create(['title' => 'گوريه','province_id'=>'13']);
        City::create(['title' => 'لالي','province_id'=>'13']);
        City::create(['title' => 'مسجدسليمان','province_id'=>'13']);
        City::create(['title' => 'مشراگه','province_id'=>'13']);
        City::create(['title' => 'مقاومت','province_id'=>'13']);
        City::create(['title' => 'ملاثاني','province_id'=>'13']);
        City::create(['title' => 'ميانرود','province_id'=>'13']);
        City::create(['title' => 'ميداود','province_id'=>'13']);
        City::create(['title' => 'مينوشهر','province_id'=>'13']);
        City::create(['title' => 'ويس','province_id'=>'13']);
        City::create(['title' => 'هفتگل','province_id'=>'13']);
        City::create(['title' => 'هنديجان','province_id'=>'13']);
        City::create(['title' => 'هويزه','province_id'=>'13']);
        City::create(['title' => 'ابهر','province_id'=>'14']);
        City::create(['title' => 'ارمغانخانه','province_id'=>'14']);
        City::create(['title' => 'آب بر','province_id'=>'14']);
        City::create(['title' => 'چورزق','province_id'=>'14']);
        City::create(['title' => 'حلب','province_id'=>'14']);
        City::create(['title' => 'خرمدره','province_id'=>'14']);
        City::create(['title' => 'دندي','province_id'=>'14']);
        City::create(['title' => 'زرين آباد','province_id'=>'14']);
        City::create(['title' => 'زرين رود','province_id'=>'14']);
        City::create(['title' => 'زنجان','province_id'=>'14']);
        City::create(['title' => 'سجاس','province_id'=>'14']);
        City::create(['title' => 'سلطانيه','province_id'=>'14']);
        City::create(['title' => 'سهرورد','province_id'=>'14']);
        City::create(['title' => 'صائين قلعه','province_id'=>'14']);
        City::create(['title' => 'قيدار','province_id'=>'14']);
        City::create(['title' => 'گرماب','province_id'=>'14']);
        City::create(['title' => 'ماه نشان','province_id'=>'14']);
        City::create(['title' => 'هيدج','province_id'=>'14']);
        City::create(['title' => 'اميريه','province_id'=>'15']);
        City::create(['title' => 'ايوانكي','province_id'=>'15']);
        City::create(['title' => 'آرادان','province_id'=>'15']);
        City::create(['title' => 'بسطام','province_id'=>'15']);
        City::create(['title' => 'بيارجمند','province_id'=>'15']);
        City::create(['title' => 'دامغان','province_id'=>'15']);
        City::create(['title' => 'درجزين','province_id'=>'15']);
        City::create(['title' => 'ديباج','province_id'=>'15']);
        City::create(['title' => 'سرخه','province_id'=>'15']);
        City::create(['title' => 'سمنان','province_id'=>'15']);
        City::create(['title' => 'شاهرود','province_id'=>'15']);
        City::create(['title' => 'شهميرزاد','province_id'=>'15']);
        City::create(['title' => 'كلاته خيج','province_id'=>'15']);
        City::create(['title' => 'گرمسار','province_id'=>'15']);
        City::create(['title' => 'مجن','province_id'=>'15']);
        City::create(['title' => 'مهدي شهر','province_id'=>'15']);
        City::create(['title' => 'ميامي','province_id'=>'15']);
        City::create(['title' => 'اديمي','province_id'=>'16']);
        City::create(['title' => 'ايرانشهر','province_id'=>'16']);
        City::create(['title' => 'بزمان','province_id'=>'16']);
        City::create(['title' => 'بمپور','province_id'=>'16']);
        City::create(['title' => 'بنت','province_id'=>'16']);
        City::create(['title' => 'بنجار','province_id'=>'16']);
        City::create(['title' => 'پيشين','province_id'=>'16']);
        City::create(['title' => 'جالق','province_id'=>'16']);
        City::create(['title' => 'چاه بهار','province_id'=>'16']);
        City::create(['title' => 'خاش','province_id'=>'16']);
        City::create(['title' => 'دوست محمد','province_id'=>'16']);
        City::create(['title' => 'راسك','province_id'=>'16']);
        City::create(['title' => 'زابل','province_id'=>'16']);
        City::create(['title' => 'زابلي','province_id'=>'16']);
        City::create(['title' => 'زاهدان','province_id'=>'16']);
        City::create(['title' => 'زرآباد','province_id'=>'16']);
        City::create(['title' => 'زهك','province_id'=>'16']);
        City::create(['title' => 'سراوان','province_id'=>'16']);
        City::create(['title' => 'سيركان','province_id'=>'16']);
        City::create(['title' => 'علي اكبر','province_id'=>'16']);
        City::create(['title' => 'فنوج','province_id'=>'16']);
        City::create(['title' => 'قصرقند','province_id'=>'16']);
        City::create(['title' => 'كنارك','province_id'=>'16']);
        City::create(['title' => 'گشت','province_id'=>'16']);
        City::create(['title' => 'گلمورتي','province_id'=>'16']);
        City::create(['title' => 'محمدان','province_id'=>'16']);
        City::create(['title' => 'محمدآباد','province_id'=>'16']);
        City::create(['title' => 'محمدي','province_id'=>'16']);
        City::create(['title' => 'ميرجاوه','province_id'=>'16']);
        City::create(['title' => 'نصرت آباد','province_id'=>'16']);
        City::create(['title' => 'ميرجاوه','province_id'=>'16']);
        City::create(['title' => 'نگور','province_id'=>'16']);
        City::create(['title' => 'نوك آباد','province_id'=>'16']);
        City::create(['title' => 'نيك شهر','province_id'=>'16']);
        City::create(['title' => 'هيدوج','province_id'=>'16']);
        City::create(['title' => 'اردكان','province_id'=>'17']);
        City::create(['title' => 'ارسنجان','province_id'=>'17']);
        City::create(['title' => 'استهبان','province_id'=>'17']);
        City::create(['title' => 'اسير','province_id'=>'17']);
        City::create(['title' => 'اشكنان','province_id'=>'17']);
        City::create(['title' => 'افزر','province_id'=>'17']);
        City::create(['title' => 'اقليد','province_id'=>'17']);
        City::create(['title' => 'امام شهر','province_id'=>'17']);
        City::create(['title' => 'اوز','province_id'=>'17']);
        City::create(['title' => 'اهل','province_id'=>'17']);
        City::create(['title' => 'ايج','province_id'=>'17']);
        City::create(['title' => 'ايزدخواست','province_id'=>'17']);
        City::create(['title' => 'آباده','province_id'=>'17']);
        City::create(['title' => 'آباده طشك','province_id'=>'17']);
        City::create(['title' => 'باب انار','province_id'=>'17']);
        City::create(['title' => 'بالاده','province_id'=>'17']);
        City::create(['title' => 'بنارويه','province_id'=>'17']);
        City::create(['title' => 'بوانات','province_id'=>'17']);
        City::create(['title' => 'بهمن','province_id'=>'17']);
        City::create(['title' => 'بيرم','province_id'=>'17']);
        City::create(['title' => 'بيضا','province_id'=>'17']);
        City::create(['title' => 'جنت شهر','province_id'=>'17']);
        City::create(['title' => 'جويم','province_id'=>'17']);
        City::create(['title' => 'جهرم','province_id'=>'17']);
        City::create(['title' => 'حاجي آباد','province_id'=>'17']);
        City::create(['title' => 'حسامي','province_id'=>'17']);
        City::create(['title' => 'حسن آباد','province_id'=>'17']);
        City::create(['title' => 'خانه زنيان','province_id'=>'17']);
        City::create(['title' => 'خاوران','province_id'=>'17']);
        City::create(['title' => 'خرامه','province_id'=>'17']);
        City::create(['title' => 'خشت','province_id'=>'17']);
        City::create(['title' => 'خنج','province_id'=>'17']);
        City::create(['title' => 'خور','province_id'=>'17']);
        City::create(['title' => 'خومه زار','province_id'=>'17']);
        City::create(['title' => 'داراب','province_id'=>'17']);
        City::create(['title' => 'داريان','province_id'=>'17']);
        City::create(['title' => 'دبيران','province_id'=>'17']);
        City::create(['title' => 'دژكرد','province_id'=>'17']);
        City::create(['title' => 'دوبرجي','province_id'=>'17']);
        City::create(['title' => 'دوزه','province_id'=>'17']);
        City::create(['title' => 'دهرم','province_id'=>'17']);
        City::create(['title' => 'رامجرد','province_id'=>'17']);
        City::create(['title' => 'رونيز','province_id'=>'17']);
        City::create(['title' => 'زاهدشهر','province_id'=>'17']);
        City::create(['title' => 'زرقان','province_id'=>'17']);
        City::create(['title' => 'سده','province_id'=>'17']);
        City::create(['title' => 'سروستان','province_id'=>'17']);
        City::create(['title' => 'سعادت شهر','province_id'=>'17']);
        City::create(['title' => 'سورمق','province_id'=>'17']);
        City::create(['title' => 'سيدان','province_id'=>'17']);
        City::create(['title' => 'ششده','province_id'=>'17']);
        City::create(['title' => 'شهر جديد صدرا','province_id'=>'17']);
        City::create(['title' => 'شهرپير','province_id'=>'17']);
        City::create(['title' => 'شيراز','province_id'=>'17']);
        City::create(['title' => 'صغاد','province_id'=>'17']);
        City::create(['title' => 'صفاشهر','province_id'=>'17']);
        City::create(['title' => 'علامرودشت','province_id'=>'17']);
        City::create(['title' => 'عمادده','province_id'=>'17']);
        City::create(['title' => 'فدامي','province_id'=>'17']);
        City::create(['title' => 'فراشبند','province_id'=>'17']);
        City::create(['title' => 'فسا','province_id'=>'17']);
        City::create(['title' => 'فيروزآباد','province_id'=>'17']);
        City::create(['title' => 'قادرآباد','province_id'=>'17']);
        City::create(['title' => 'قطب آباد','province_id'=>'17']);
        City::create(['title' => 'قطرويه','province_id'=>'17']);
        City::create(['title' => 'قير','province_id'=>'17']);
        City::create(['title' => 'قطرويه','province_id'=>'17']);
        City::create(['title' => 'كارزين','province_id'=>'17']);
        City::create(['title' => 'كازرون','province_id'=>'17']);
        City::create(['title' => 'كامفيروز','province_id'=>'17']);
        City::create(['title' => 'كره اي','province_id'=>'17']);
        City::create(['title' => 'كنارتخته','province_id'=>'17']);
        City::create(['title' => 'كوار','province_id'=>'17']);
        City::create(['title' => 'كوهنجان','province_id'=>'17']);
        City::create(['title' => 'گراش','province_id'=>'17']);
        City::create(['title' => 'گله دار','province_id'=>'17']);
        City::create(['title' => 'لار','province_id'=>'17']);
        City::create(['title' => 'لامرد','province_id'=>'17']);
        City::create(['title' => 'لپوئي','province_id'=>'17']);
        City::create(['title' => 'لطيفي','province_id'=>'17']);
        City::create(['title' => 'مبارك آباد','province_id'=>'17']);
        City::create(['title' => 'مرودشت','province_id'=>'17']);
        City::create(['title' => 'مشكان','province_id'=>'17']);
        City::create(['title' => 'مصيري','province_id'=>'17']);
        City::create(['title' => 'مهر','province_id'=>'17']);
        City::create(['title' => 'ميمند','province_id'=>'17']);
        City::create(['title' => 'نوبندگان','province_id'=>'17']);
        City::create(['title' => 'نوجين','province_id'=>'17']);
        City::create(['title' => 'ميمند','province_id'=>'17']);
        City::create(['title' => 'نودان','province_id'=>'17']);
        City::create(['title' => 'نورآباد','province_id'=>'17']);
        City::create(['title' => 'ني ريز','province_id'=>'17']);
        City::create(['title' => 'وراوي','province_id'=>'17']);
        City::create(['title' => 'هماشهر','province_id'=>'17']);
        City::create(['title' => 'ارداق','province_id'=>'18']);
        City::create(['title' => 'اسفرورين','province_id'=>'18']);
        City::create(['title' => 'اقباليه','province_id'=>'18']);
        City::create(['title' => 'الوند','province_id'=>'18']);
        City::create(['title' => 'آبگرم','province_id'=>'18']);
        City::create(['title' => 'آبيك','province_id'=>'18']);
        City::create(['title' => 'آوج','province_id'=>'18']);
        City::create(['title' => 'بوئين زهرا','province_id'=>'18']);
        City::create(['title' => 'بيدستان','province_id'=>'18']);
        City::create(['title' => 'تاكستان','province_id'=>'18']);
        City::create(['title' => 'خاكعلي','province_id'=>'18']);
        City::create(['title' => 'خرمدشت','province_id'=>'18']);
        City::create(['title' => 'دانسفهان','province_id'=>'18']);
        City::create(['title' => 'رازميان','province_id'=>'18']);
        City::create(['title' => 'سگزآباد','province_id'=>'18']);
        City::create(['title' => 'سيردان','province_id'=>'18']);
        City::create(['title' => 'شال','province_id'=>'18']);
        City::create(['title' => 'شريفيه','province_id'=>'18']);
        City::create(['title' => 'ضياءآباد','province_id'=>'18']);
        City::create(['title' => 'قزوين','province_id'=>'18']);
        City::create(['title' => 'كوهين','province_id'=>'18']);
        City::create(['title' => 'محمديه','province_id'=>'18']);
        City::create(['title' => 'محمودآبادنمونه','province_id'=>'18']);
        City::create(['title' => 'معلم كلايه','province_id'=>'18']);
        City::create(['title' => 'نرجه','province_id'=>'18']);
        City::create(['title' => 'جعفريه','province_id'=>'19']);
        City::create(['title' => 'دستجرد','province_id'=>'19']);
        City::create(['title' => 'سلفچگان','province_id'=>'19']);
        City::create(['title' => 'قم','province_id'=>'19']);
        City::create(['title' => 'قنوات','province_id'=>'19']);
        City::create(['title' => 'كهك','province_id'=>'19']);
        City::create(['title' => 'آرمرده','province_id'=>'20']);
        City::create(['title' => 'بابارشاني','province_id'=>'20']);
        City::create(['title' => 'بانه','province_id'=>'20']);
        City::create(['title' => 'بلبان آباد','province_id'=>'20']);
        City::create(['title' => 'بوئين سفلي','province_id'=>'20']);
        City::create(['title' => 'بيجار','province_id'=>'20']);
        City::create(['title' => 'چناره','province_id'=>'20']);
        City::create(['title' => 'دزج','province_id'=>'20']);
        City::create(['title' => 'دلبران','province_id'=>'20']);
        City::create(['title' => 'دهگلان','province_id'=>'20']);
        City::create(['title' => 'ديواندره','province_id'=>'20']);
        City::create(['title' => 'زرينه','province_id'=>'20']);
        City::create(['title' => 'سروآباد','province_id'=>'20']);
        City::create(['title' => 'سريش آباد','province_id'=>'20']);
        City::create(['title' => 'سقز','province_id'=>'20']);
        City::create(['title' => 'سنندج','province_id'=>'20']);
        City::create(['title' => 'شويشه','province_id'=>'20']);
        City::create(['title' => 'صاحب','province_id'=>'20']);
        City::create(['title' => 'قروه','province_id'=>'20']);
        City::create(['title' => 'كامياران','province_id'=>'20']);
        City::create(['title' => 'كاني دينار','province_id'=>'20']);
        City::create(['title' => 'كاني سور','province_id'=>'20']);
        City::create(['title' => 'مريوان','province_id'=>'20']);
        City::create(['title' => 'موچش','province_id'=>'20']);
        City::create(['title' => 'ياسوكند','province_id'=>'20']);
        City::create(['title' => 'اختيارآباد','province_id'=>'21']);
        City::create(['title' => 'ارزوئيه','province_id'=>'21']);
        City::create(['title' => 'امين شهر','province_id'=>'21']);
        City::create(['title' => 'انار','province_id'=>'21']);
        City::create(['title' => 'اندوهجرد','province_id'=>'21']);
        City::create(['title' => 'باغين','province_id'=>'21']);
        City::create(['title' => 'بافت','province_id'=>'21']);
        City::create(['title' => 'بردسير','province_id'=>'21']);
        City::create(['title' => 'بروات','province_id'=>'21']);
        City::create(['title' => 'بزنجان','province_id'=>'21']);
        City::create(['title' => 'بم','province_id'=>'21']);
        City::create(['title' => 'بهرمان','province_id'=>'21']);
        City::create(['title' => 'پاريز','province_id'=>'21']);
        City::create(['title' => 'جبالبارز','province_id'=>'21']);
        City::create(['title' => 'جوپار','province_id'=>'21']);
        City::create(['title' => 'جوزم','province_id'=>'21']);
        City::create(['title' => 'جيرفت','province_id'=>'21']);
        City::create(['title' => 'چترود','province_id'=>'21']);
        City::create(['title' => 'خاتون آباد','province_id'=>'21']);
        City::create(['title' => 'خانوك','province_id'=>'21']);
        City::create(['title' => 'خورسند','province_id'=>'21']);
        City::create(['title' => 'درب بهشت','province_id'=>'21']);
        City::create(['title' => 'دوساري','province_id'=>'21']);
        City::create(['title' => 'دهج','province_id'=>'21']);
        City::create(['title' => 'رابر','province_id'=>'21']);
        City::create(['title' => 'راور','province_id'=>'21']);
        City::create(['title' => 'راين','province_id'=>'21']);
        City::create(['title' => 'رفسنجان','province_id'=>'21']);
        City::create(['title' => 'رودبار','province_id'=>'21']);
        City::create(['title' => 'ريحان شهر','province_id'=>'21']);
        City::create(['title' => 'زرند','province_id'=>'21']);
        City::create(['title' => 'زنگي آباد','province_id'=>'21']);
        City::create(['title' => 'زيدآباد','province_id'=>'21']);
        City::create(['title' => 'سرچشمه','province_id'=>'21']);
        City::create(['title' => 'سيرجان','province_id'=>'21']);
        City::create(['title' => 'شهداد','province_id'=>'21']);
        City::create(['title' => 'شهربابك','province_id'=>'21']);
        City::create(['title' => 'صفائيه','province_id'=>'21']);
        City::create(['title' => 'عنبرآباد','province_id'=>'21']);
        City::create(['title' => 'فارياب','province_id'=>'21']);
        City::create(['title' => 'فهرج','province_id'=>'21']);
        City::create(['title' => 'قلعه گنج','province_id'=>'21']);
        City::create(['title' => 'كاظم آباد','province_id'=>'21']);
        City::create(['title' => 'کرمان','province_id'=>'21']);
        City::create(['title' => 'كشكوئيه','province_id'=>'21']);
        City::create(['title' => 'كوهبنان','province_id'=>'21']);
        City::create(['title' => 'كهنوج','province_id'=>'21']);
        City::create(['title' => 'كيانشهر','province_id'=>'21']);
        City::create(['title' => 'گلباف','province_id'=>'21']);
        City::create(['title' => 'گلزار','province_id'=>'21']);
        City::create(['title' => 'لاله زار','province_id'=>'21']);
        City::create(['title' => 'ماهان','province_id'=>'21']);
        City::create(['title' => 'محمدآباد','province_id'=>'21']);
        City::create(['title' => 'محي آباد','province_id'=>'21']);
        City::create(['title' => 'مردهك','province_id'=>'21']);
        City::create(['title' => 'منوجان','province_id'=>'21']);
        City::create(['title' => 'نجف شهر','province_id'=>'21']);
        City::create(['title' => 'نرماشير','province_id'=>'21']);
        City::create(['title' => 'نظام شهر','province_id'=>'21']);
        City::create(['title' => 'نگار','province_id'=>'21']);
        City::create(['title' => 'نودژ','province_id'=>'21']);
        City::create(['title' => 'هجدك','province_id'=>'21']);
        City::create(['title' => 'هماشهر','province_id'=>'21']);
        City::create(['title' => 'يزدان شهر','province_id'=>'21']);
        City::create(['title' => 'ازگله','province_id'=>'22']);
        City::create(['title' => 'اسلام آبادغرب','province_id'=>'22']);
        City::create(['title' => 'باينگان','province_id'=>'22']);
        City::create(['title' => 'بيستون','province_id'=>'22']);
        City::create(['title' => 'پاوه','province_id'=>'22']);
        City::create(['title' => 'تازه آباد','province_id'=>'22']);
        City::create(['title' => 'جوانرود','province_id'=>'22']);
        City::create(['title' => 'حميل','province_id'=>'22']);
        City::create(['title' => 'رباط','province_id'=>'22']);
        City::create(['title' => 'روانسر','province_id'=>'22']);
        City::create(['title' => 'سرپل ذهاب','province_id'=>'22']);
        City::create(['title' => 'سرمست','province_id'=>'22']);
        City::create(['title' => 'سطر','province_id'=>'22']);
        City::create(['title' => 'سنقر','province_id'=>'22']);
        City::create(['title' => 'سومار','province_id'=>'22']);
        City::create(['title' => 'شاهو','province_id'=>'22']);
        City::create(['title' => 'صحنه','province_id'=>'22']);
        City::create(['title' => 'قصرشيرين','province_id'=>'22']);
        City::create(['title' => 'کرمانشاه','province_id'=>'22']);
        City::create(['title' => 'كرندغرب','province_id'=>'22']);
        City::create(['title' => 'كنگاور','province_id'=>'22']);
        City::create(['title' => 'كوزران','province_id'=>'22']);
        City::create(['title' => 'گهواره','province_id'=>'22']);
        City::create(['title' => 'گيلانغرب','province_id'=>'22']);
        City::create(['title' => 'ميان راهان','province_id'=>'22']);
        City::create(['title' => 'نودشه','province_id'=>'22']);
        City::create(['title' => 'نوسود','province_id'=>'22']);
        City::create(['title' => 'هرسين','province_id'=>'22']);
        City::create(['title' => 'هلشي','province_id'=>'22']);
        City::create(['title' => 'باشت','province_id'=>'23']);
        City::create(['title' => 'پاتاوه','province_id'=>'23']);
        City::create(['title' => 'چرام','province_id'=>'23']);
        City::create(['title' => 'چيتاب','province_id'=>'23']);
        City::create(['title' => 'دوگنبدان','province_id'=>'23']);
        City::create(['title' => 'دهدشت','province_id'=>'23']);
        City::create(['title' => 'ديشموك','province_id'=>'23']);
        City::create(['title' => 'سوق','province_id'=>'23']);
        City::create(['title' => 'سي سخت','province_id'=>'23']);
        City::create(['title' => 'قلعه رئيسي','province_id'=>'23']);
        City::create(['title' => 'گراب سفلي','province_id'=>'23']);
        City::create(['title' => 'لنده','province_id'=>'23']);
        City::create(['title' => 'ليكك','province_id'=>'23']);
        City::create(['title' => 'مادوان','province_id'=>'23']);
        City::create(['title' => 'مارگون','province_id'=>'23']);
        City::create(['title' => 'ياسوج','province_id'=>'23']);
        City::create(['title' => 'انبارآلوم','province_id'=>'24']);
        City::create(['title' => 'اينچه برون','province_id'=>'24']);
        City::create(['title' => 'آزادشهر','province_id'=>'24']);
        City::create(['title' => 'آق قلا','province_id'=>'24']);
        City::create(['title' => 'بندرگز','province_id'=>'24']);
        City::create(['title' => 'تركمن','province_id'=>'24']);
        City::create(['title' => 'جلين','province_id'=>'24']);
        City::create(['title' => 'خان ببين','province_id'=>'24']);
        City::create(['title' => 'دلند','province_id'=>'24']);
        City::create(['title' => 'راميان','province_id'=>'24']);
        City::create(['title' => 'سرخنكلاته','province_id'=>'24']);
        City::create(['title' => 'سيمين شهر','province_id'=>'24']);
        City::create(['title' => 'علي آباد','province_id'=>'24']);
        City::create(['title' => 'فاضل آباد','province_id'=>'24']);
        City::create(['title' => 'كردكوي','province_id'=>'24']);
        City::create(['title' => 'كلاله','province_id'=>'24']);
        City::create(['title' => 'گاليكش','province_id'=>'24']);
        City::create(['title' => 'گرگان','province_id'=>'24']);
        City::create(['title' => 'گميش تپه','province_id'=>'24']);
        City::create(['title' => 'گنبد كاووس','province_id'=>'24']);
        City::create(['title' => 'مينودشت','province_id'=>'24']);
        City::create(['title' => 'نگين شهر','province_id'=>'24']);
        City::create(['title' => 'نوده خاندوز','province_id'=>'24']);
        City::create(['title' => 'نوكنده','province_id'=>'24']);
        City::create(['title' => 'احمدسرگوراب','province_id'=>'25']);
        City::create(['title' => 'اسالم','province_id'=>'25']);
        City::create(['title' => 'اطاقور','province_id'=>'25']);
        City::create(['title' => 'املش','province_id'=>'25']);
        City::create(['title' => 'آستارا','province_id'=>'25']);
        City::create(['title' => 'آستانه اشرفيه','province_id'=>'25']);
        City::create(['title' => 'بازارجمعه','province_id'=>'25']);
        City::create(['title' => 'بره سر','province_id'=>'25']);
        City::create(['title' => 'توتكابن','province_id'=>'25']);
        City::create(['title' => 'جيرنده','province_id'=>'25']);
        City::create(['title' => 'چابكسر','province_id'=>'25']);
        City::create(['title' => 'چاف وچمخاله','province_id'=>'25']);
        City::create(['title' => 'چوبر','province_id'=>'25']);
        City::create(['title' => 'حويق','province_id'=>'25']);
        City::create(['title' => 'خشكبيجار','province_id'=>'25']);
        City::create(['title' => 'خمام','province_id'=>'25']);
        City::create(['title' => 'ديلمان','province_id'=>'25']);
        City::create(['title' => 'رانكوه','province_id'=>'25']);
        City::create(['title' => 'رحيم آباد','province_id'=>'25']);
        City::create(['title' => 'رستم آباد','province_id'=>'25']);
        City::create(['title' => 'رشت','province_id'=>'25']);
        City::create(['title' => 'رضوانشهر','province_id'=>'25']);
        City::create(['title' => 'رودبار','province_id'=>'25']);
        City::create(['title' => 'رودبنه','province_id'=>'25']);
        City::create(['title' => 'رودسر','province_id'=>'25']);
        City::create(['title' => 'سنگر','province_id'=>'25']);
        City::create(['title' => 'سياهكل','province_id'=>'25']);
        City::create(['title' => 'شفت','province_id'=>'25']);
        City::create(['title' => 'شلمان','province_id'=>'25']);
        City::create(['title' => 'صومعه سرا','province_id'=>'25']);
        City::create(['title' => 'فومن','province_id'=>'25']);
        City::create(['title' => 'كلاچاي','province_id'=>'25']);
        City::create(['title' => 'كوچصفهان','province_id'=>'25']);
        City::create(['title' => 'كومله','province_id'=>'25']);
        City::create(['title' => 'كياشهر','province_id'=>'25']);
        City::create(['title' => 'گوراب زرميخ','province_id'=>'25']);
        City::create(['title' => 'لاهيجان','province_id'=>'25']);
        City::create(['title' => 'لشت نشاء','province_id'=>'25']);
        City::create(['title' => 'لنگرود','province_id'=>'25']);
        City::create(['title' => 'لوشان','province_id'=>'25']);
        City::create(['title' => 'لولمان','province_id'=>'25']);
        City::create(['title' => 'لوندويل','province_id'=>'25']);
        City::create(['title' => 'ليسار','province_id'=>'25']);
        City::create(['title' => 'ماسال','province_id'=>'25']);
        City::create(['title' => 'ماسوله','province_id'=>'25']);
        City::create(['title' => 'مرجقل','province_id'=>'25']);
        City::create(['title' => 'منجيل','province_id'=>'25']);
        City::create(['title' => 'واجارگاه','province_id'=>'25']);
        City::create(['title' => 'هشتپر','province_id'=>'25']);
        City::create(['title' => 'ازنا','province_id'=>'26']);
        City::create(['title' => 'اشترينان','province_id'=>'26']);
        City::create(['title' => 'الشتر','province_id'=>'26']);
        City::create(['title' => 'اليگودرز','province_id'=>'26']);
        City::create(['title' => 'بروجرد','province_id'=>'26']);
        City::create(['title' => 'پلدختر','province_id'=>'26']);
        City::create(['title' => 'چالانچولان','province_id'=>'26']);
        City::create(['title' => 'چغلوندي','province_id'=>'26']);
        City::create(['title' => 'چقابل','province_id'=>'26']);
        City::create(['title' => 'خرم آباد','province_id'=>'26']);
        City::create(['title' => 'درب گنبد','province_id'=>'26']);
        City::create(['title' => 'دورود','province_id'=>'26']);
        City::create(['title' => 'زاغه','province_id'=>'26']);
        City::create(['title' => 'سپيددشت','province_id'=>'26']);
        City::create(['title' => 'سراب دوره','province_id'=>'26']);
        City::create(['title' => 'شول آباد','province_id'=>'26']);
        City::create(['title' => 'فيروزآباد','province_id'=>'26']);
        City::create(['title' => 'كوناني','province_id'=>'26']);
        City::create(['title' => 'كوهدشت','province_id'=>'26']);
        City::create(['title' => 'گراب','province_id'=>'26']);
        City::create(['title' => 'معمولان','province_id'=>'26']);
        City::create(['title' => 'مؤمن آباد','province_id'=>'26']);
        City::create(['title' => 'نورآباد','province_id'=>'26']);
        City::create(['title' => 'ويسيان','province_id'=>'26']);
        City::create(['title' => 'هفت چشمه','province_id'=>'26']);
        City::create(['title' => 'اميركلا','province_id'=>'27']);
        City::create(['title' => 'ايزدشهر','province_id'=>'27']);
        City::create(['title' => 'آلاشت','province_id'=>'27']);
        City::create(['title' => 'آمل','province_id'=>'27']);
        City::create(['title' => 'بابل','province_id'=>'27']);
        City::create(['title' => 'بابلسر','province_id'=>'27']);
        City::create(['title' => 'بلده','province_id'=>'27']);
        City::create(['title' => 'بهشهر','province_id'=>'27']);
        City::create(['title' => 'بهنمير','province_id'=>'27']);
        City::create(['title' => 'پل سفيد','province_id'=>'27']);
        City::create(['title' => 'پول','province_id'=>'27']);
        City::create(['title' => 'تنكابن','province_id'=>'27']);
        City::create(['title' => 'جويبار','province_id'=>'27']);
        City::create(['title' => 'چالوس','province_id'=>'27']);
        City::create(['title' => 'چمستان','province_id'=>'27']);
        City::create(['title' => 'خرم آباد','province_id'=>'27']);
        City::create(['title' => 'خليل شهر','province_id'=>'27']);
        City::create(['title' => 'خوش رودپي','province_id'=>'27']);
        City::create(['title' => 'دابودشت','province_id'=>'27']);
        City::create(['title' => 'رامسر','province_id'=>'27']);
        City::create(['title' => 'رستمكلا','province_id'=>'27']);
        City::create(['title' => 'رويان','province_id'=>'27']);
        City::create(['title' => 'رينه','province_id'=>'27']);
        City::create(['title' => 'زرگر محله','province_id'=>'27']);
        City::create(['title' => 'زيرآب','province_id'=>'27']);
        City::create(['title' => 'ساري','province_id'=>'27']);
        City::create(['title' => 'سرخرود','province_id'=>'27']);
        City::create(['title' => 'سلمان شهر','province_id'=>'27']);
        City::create(['title' => 'سورك','province_id'=>'27']);
        City::create(['title' => 'شيرگاه','province_id'=>'27']);
        City::create(['title' => 'شيرود','province_id'=>'27']);
        City::create(['title' => 'عباس آباد','province_id'=>'27']);
        City::create(['title' => 'فريدونكنار','province_id'=>'27']);
        City::create(['title' => 'فريم','province_id'=>'27']);
        City::create(['title' => 'قائم شهر','province_id'=>'27']);
        City::create(['title' => 'كتالم وسادات شهر','province_id'=>'27']);
        City::create(['title' => 'كلارآباد','province_id'=>'27']);
        City::create(['title' => 'كلاردشت','province_id'=>'27']);
        City::create(['title' => 'كله بست','province_id'=>'27']);
        City::create(['title' => 'كوهي خيل','province_id'=>'27']);
        City::create(['title' => 'كياسر','province_id'=>'27']);
        City::create(['title' => 'كياكلا','province_id'=>'27']);
        City::create(['title' => 'گتاب','province_id'=>'27']);
        City::create(['title' => 'گزنك','province_id'=>'27']);
        City::create(['title' => 'گلوگاه','province_id'=>'27']);
        City::create(['title' => 'محمودآباد','province_id'=>'27']);
        City::create(['title' => 'مرزن آباد','province_id'=>'27']);
        City::create(['title' => 'مرزيكلا','province_id'=>'27']);
        City::create(['title' => 'نشتارود','province_id'=>'27']);
        City::create(['title' => 'نكا','province_id'=>'27']);
        City::create(['title' => 'نور','province_id'=>'27']);
        City::create(['title' => 'نوشهر','province_id'=>'27']);
        City::create(['title' => 'اراك','province_id'=>'28']);
        City::create(['title' => 'آستانه','province_id'=>'28']);
        City::create(['title' => 'آشتيان','province_id'=>'28']);
        City::create(['title' => 'پرندك','province_id'=>'28']);
        City::create(['title' => 'تفرش','province_id'=>'28']);
        City::create(['title' => 'جاورسيان','province_id'=>'28']);
        City::create(['title' => 'خشكرود','province_id'=>'28']);
        City::create(['title' => 'خمين','province_id'=>'28']);
        City::create(['title' => 'خنداب','province_id'=>'28']);
        City::create(['title' => 'داودآباد','province_id'=>'28']);
        City::create(['title' => 'دليجان','province_id'=>'28']);
        City::create(['title' => 'رازقان','province_id'=>'28']);
        City::create(['title' => 'زاويه','province_id'=>'28']);
        City::create(['title' => 'ساروق','province_id'=>'28']);
        City::create(['title' => 'ساوه','province_id'=>'28']);
        City::create(['title' => 'سنجان','province_id'=>'28']);
        City::create(['title' => 'شازند','province_id'=>'28']);
        City::create(['title' => 'شهرجديدمهاجران','province_id'=>'28']);
        City::create(['title' => 'فرمهين','province_id'=>'28']);
        City::create(['title' => 'قورچي باشي','province_id'=>'28']);
        City::create(['title' => 'كميجان','province_id'=>'28']);
        City::create(['title' => 'مأمونيه','province_id'=>'28']);
        City::create(['title' => 'محلات','province_id'=>'28']);
        City::create(['title' => 'ميلاجرد','province_id'=>'28']);
        City::create(['title' => 'نراق','province_id'=>'28']);
        City::create(['title' => 'نوبران','province_id'=>'28']);
        City::create(['title' => 'نيمور','province_id'=>'28']);
        City::create(['title' => 'هندودر','province_id'=>'28']);
        City::create(['title' => 'ابوموسي','province_id'=>'29']);
        City::create(['title' => 'بستك','province_id'=>'29']);
        City::create(['title' => 'بندرجاسك','province_id'=>'29']);
        City::create(['title' => 'بندرچارك','province_id'=>'29']);
        City::create(['title' => 'بندرعباس','province_id'=>'29']);
        City::create(['title' => 'بندرلنگه','province_id'=>'29']);
        City::create(['title' => 'پارسيان','province_id'=>'29']);
        City::create(['title' => 'تخت','province_id'=>'29']);
        City::create(['title' => 'جناح','province_id'=>'29']);
        City::create(['title' => 'حاجي آباد','province_id'=>'29']);
        City::create(['title' => 'خمير','province_id'=>'29']);
        City::create(['title' => 'درگهان','province_id'=>'29']);
        City::create(['title' => 'دهبارز','province_id'=>'29']);
        City::create(['title' => 'رويدر','province_id'=>'29']);
        City::create(['title' => 'زيارتعلي','province_id'=>'29']);
        City::create(['title' => 'سردشت بشاگرد','province_id'=>'29']);
        City::create(['title' => 'سرگز','province_id'=>'29']);
        City::create(['title' => 'سندرك','province_id'=>'29']);
        City::create(['title' => 'سوزا','province_id'=>'29']);
        City::create(['title' => 'سيريك','province_id'=>'29']);
        City::create(['title' => 'فارغان','province_id'=>'29']);
        City::create(['title' => 'فين','province_id'=>'29']);
        City::create(['title' => 'قشم','province_id'=>'29']);
        City::create(['title' => 'قلعه قاضي','province_id'=>'29']);
        City::create(['title' => 'كنگ','province_id'=>'29']);
        City::create(['title' => 'كوشكنار','province_id'=>'29']);
        City::create(['title' => 'كيش','province_id'=>'29']);
        City::create(['title' => 'گوهران','province_id'=>'29']);
        City::create(['title' => 'ميناب','province_id'=>'29']);
        City::create(['title' => 'هرمز','province_id'=>'29']);
        City::create(['title' => 'هشتبندي','province_id'=>'29']);
        City::create(['title' => 'ازندريان','province_id'=>'30']);
        City::create(['title' => 'اسدآباد','province_id'=>'30']);
        City::create(['title' => 'برزول','province_id'=>'30']);
        City::create(['title' => 'بهار','province_id'=>'30']);
        City::create(['title' => 'تويسركان','province_id'=>'30']);
        City::create(['title' => 'جورقان','province_id'=>'30']);
        City::create(['title' => 'جوكار','province_id'=>'30']);
        City::create(['title' => 'دمق','province_id'=>'30']);
        City::create(['title' => 'رزن','province_id'=>'30']);
        City::create(['title' => 'زنگنه','province_id'=>'30']);
        City::create(['title' => 'سامن','province_id'=>'30']);
        City::create(['title' => 'سركان','province_id'=>'30']);
        City::create(['title' => 'شيرين سو','province_id'=>'30']);
        City::create(['title' => 'صالح آباد','province_id'=>'30']);
        City::create(['title' => 'فامنين','province_id'=>'30']);
        City::create(['title' => 'فرسفج','province_id'=>'30']);
        City::create(['title' => 'فيروزان','province_id'=>'30']);
        City::create(['title' => 'قروه در جزين','province_id'=>'30']);
        City::create(['title' => 'قهاوند','province_id'=>'30']);
        City::create(['title' => 'كبودرآهنگ','province_id'=>'30']);
        City::create(['title' => 'گل تپه','province_id'=>'30']);
        City::create(['title' => 'گيان','province_id'=>'30']);
        City::create(['title' => 'لالجين','province_id'=>'30']);
        City::create(['title' => 'مريانج','province_id'=>'30']);
        City::create(['title' => 'ملاير','province_id'=>'30']);
        City::create(['title' => 'نهاوند','province_id'=>'30']);
        City::create(['title' => 'همدان','province_id'=>'30']);
        City::create(['title' => 'ابركوه','province_id'=>'31']);
        City::create(['title' => 'احمدآباد','province_id'=>'31']);
        City::create(['title' => 'اردكان','province_id'=>'31']);
        City::create(['title' => 'اشكذر','province_id'=>'31']);
        City::create(['title' => 'بفروئيه','province_id'=>'31']);
        City::create(['title' => 'بهاباد','province_id'=>'31']);
        City::create(['title' => 'تفت','province_id'=>'31']);
        City::create(['title' => 'حميديا','province_id'=>'31']);
        City::create(['title' => 'خضرآباد','province_id'=>'31']);
        City::create(['title' => 'ديهوك','province_id'=>'31']);
        City::create(['title' => 'شاهديه','province_id'=>'31']);
        City::create(['title' => 'عشق آباد','province_id'=>'31']);
        City::create(['title' => 'عقدا','province_id'=>'31']);
        City::create(['title' => 'مروست','province_id'=>'31']);
        City::create(['title' => 'مهردشت','province_id'=>'31']);
        City::create(['title' => 'مهريز','province_id'=>'31']);
        City::create(['title' => 'ميبد','province_id'=>'31']);
        City::create(['title' => 'ندوشن','province_id'=>'31']);
        City::create(['title' => 'نير','province_id'=>'31']);
        City::create(['title' => 'هرات','province_id'=>'31']);
        City::create(['title' => 'یزد','province_id'=>'31']);
    }
}
